//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Framework.Management.ResourceLibrary;
using AutoMapper;
using Dwp.Adep.Framework.Management.Web.Helpers;
using Dwp.Adep.Framework.Management.Web.ViewModels;
using Dwp.Adep.Framework.Management.Web.Models;
using Dwp.Adep.Framework.Management.Web.AdminService;


namespace Dwp.Adep.Framework.Management.Web.Controllers
{
    public partial class AuditController : BaseController
    {
		#region Edit
		
        // GET: /Audit/Edit
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = SessionManager.AuditCode;
			
            AuditVM model = new AuditVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.AuditItem = new AuditModel();                              
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to get Audit item and any associated lookups    
                    AuditVMDC returnedObject = sc.GetAudit(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					sc.Close();

                    //Get view model from service
                    model = ConvertAuditDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    SessionManager.AuditServiceVersion = model.AuditItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved Audit to session
            SessionManager.CurrentAudit = model.AuditItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /Audit/Edit with Create button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateAudit(FormCollection collection)
        {
            return UpdateAudit();
        }

        // POST: /Audit/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveAudit(FormCollection collection)
        {
            return UpdateAudit();
        }

        //This method is shared between create and save
        private ActionResult UpdateAudit()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    AuditDC AuditItem = Mapper.Map<AuditDC>(model.AuditItem);

					AuditVMDC returnedObject = null;

                    if (null == model.AuditItem.Code || model.AuditItem.Code == Guid.Empty)
                    {
						// Call service to create new Audit item
                        returnedObject = sc.CreateAudit(CurrentUser, CurrentUser, appID, "", AuditItem);
                    }
                    else
                    {
						// Call service to update Audit item
                        returnedObject = sc.UpdateAudit(CurrentUser, CurrentUser, appID, "", AuditItem);
                    }

					// Close service communication
					sc.Close();
					
					// Retrieve item returned by service
                    var createdAudit = returnedObject.AuditItem;

					// Map data contract to model
                    model.AuditItem = Mapper.Map<AuditModel>(createdAudit);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = AuditAccessContext.Edit;

					// Save version of item returned by service into session
                    SessionManager.AuditServiceVersion = model.AuditItem;
                    SessionManager.CurrentAudit = model.AuditItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = FixedResources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /Audit/Edit with Exit button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitAudit(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                SessionManager.CurrentAudit = null;
                SessionManager.AuditServiceVersion = null;

                return RedirectToAction("Search", "Audit");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region Delete

        // POST: /Audit/Edit with Delete button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult DeleteAudit(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsDeleteConfirmed == "True")
            {
                //Set flags false
                SetFlagsFalse(model);
            
                model.IsDeleteConfirmed = "False";
				
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to delete the item
                    sc.DeleteAudit(CurrentUser, CurrentUser, appID, "", model.AuditItem.Code.ToString(), model.AuditItem.RowIdentifier.ToString());

					// Close service communication
					sc.Close();
					
                    // Remove the current values from session
                    SessionManager.CurrentAudit = null;
                    SessionManager.AuditServiceVersion = null;

					// Redirect to the search screen
                    return RedirectToAction("Search", "Audit");
                }
				catch (Exception e)
                {
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
                }
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_DELETECONFIRMATION;
                model.IsDeleteConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /Audit/Edit with New button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewAudit(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			SessionManager.AuditCode = null;
            SessionManager.CurrentAudit = null;
            SessionManager.AuditServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "Audit");
        }
		
		#endregion

		#region Search

        // GET: /Audit/Search
        //This is called when first entering search Audit screen or when paging
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			AdminServiceClient sc = new AdminServiceClient();
			
			// Create model
			AuditSearchVM model = new AuditSearchVM();
			
			try
			{
				AuditSearchVMDC response = sc.SearchAudit(CurrentUser, CurrentUser, appID, "", null, page, PageSize, true);

				// Close service communication
				sc.Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<AuditSearchMatchDC>, List<AuditSearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = SessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				SessionManager.AuditPageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /Audit/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(AuditSearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					SessionManager.AuditCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "Audit", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(AuditVM model)
        {
            model.IsDeleteConfirmed = "False";
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(AuditVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private AuditVM GetUpdatedModel()
        {
            AuditVM model = new AuditVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (SessionManager.CurrentAudit != null)
            {
                model.AuditItem = SessionManager.CurrentAudit;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (SessionManager.CurrentAudit != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.AuditItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private AuditVM ConvertAuditDC(AuditVMDC returnedObject)
        {
            AuditVM model = new AuditVM();
            
			// Map Audit Item
			model.AuditItem = Mapper.Map<AuditDC, AuditModel>(returnedObject.AuditItem);
            
			// Map lookup data lists
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(AuditVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            AuditLookupListsCacheObject CachedLists = CacheManager.AuditListCache;

			// Retrieve any cached lists to model
   
        }

        private void MergeNewValuesWithOriginal(AuditModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            AuditModel OriginalValuesFromSession = SessionManager.CurrentAudit;

        }
		
		private void SetAccessContext(AuditVM model)
        {
            //Decide on access context
            if (null == model.AuditItem || model.AuditItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = AuditAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = AuditAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(AuditVM model)
        {
            //Compare the Audit to the original session
            if (model.AuditItem.PublicInstancePropertiesEqual(SessionManager.AuditServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
