//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Framework.Management.ResourceLibrary;
using AutoMapper;
using Dwp.Adep.Framework.Management.Web.Helpers;
using Dwp.Adep.Framework.Management.Web.ViewModels;
using Dwp.Adep.Framework.Management.Web.Models;
using Dwp.Adep.Framework.Management.Web.AdminService;


namespace Dwp.Adep.Framework.Management.Web.Controllers
{
    public partial class OrganisationHierarchyController : BaseController
    {
		#region Edit
		
        // GET: /OrganisationHierarchy/Edit
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = SessionManager.OrganisationHierarchyCode;
			
            OrganisationHierarchyVM model = new OrganisationHierarchyVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.OrganisationHierarchyItem = new OrganisationHierarchyModel();                              
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to get OrganisationHierarchy item and any associated lookups    
                    OrganisationHierarchyVMDC returnedObject = sc.GetOrganisationHierarchy(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					sc.Close();

                    //Get view model from service
                    model = ConvertOrganisationHierarchyDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    SessionManager.OrganisationHierarchyServiceVersion = model.OrganisationHierarchyItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved OrganisationHierarchy to session
            SessionManager.CurrentOrganisationHierarchy = model.OrganisationHierarchyItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /OrganisationHierarchy/Edit with Create button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateOrganisationHierarchy(FormCollection collection)
        {
            return UpdateOrganisationHierarchy();
        }

        // POST: /OrganisationHierarchy/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveOrganisationHierarchy(FormCollection collection)
        {
            return UpdateOrganisationHierarchy();
        }

        //This method is shared between create and save
        private ActionResult UpdateOrganisationHierarchy()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    OrganisationHierarchyDC OrganisationHierarchyItem = Mapper.Map<OrganisationHierarchyDC>(model.OrganisationHierarchyItem);

					OrganisationHierarchyVMDC returnedObject = null;

                    if (null == model.OrganisationHierarchyItem.Code || model.OrganisationHierarchyItem.Code == Guid.Empty)
                    {
						// Call service to create new OrganisationHierarchy item
                        returnedObject = sc.CreateOrganisationHierarchy(CurrentUser, CurrentUser, appID, "", OrganisationHierarchyItem);
                    }
                    else
                    {
						// Call service to update OrganisationHierarchy item
                        returnedObject = sc.UpdateOrganisationHierarchy(CurrentUser, CurrentUser, appID, "", OrganisationHierarchyItem);
                    }

					// Close service communication
					sc.Close();
					
					// Retrieve item returned by service
                    var createdOrganisationHierarchy = returnedObject.OrganisationHierarchyItem;

					// Map data contract to model
                    model.OrganisationHierarchyItem = Mapper.Map<OrganisationHierarchyModel>(createdOrganisationHierarchy);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = OrganisationHierarchyAccessContext.Edit;

					// Save version of item returned by service into session
                    SessionManager.OrganisationHierarchyServiceVersion = model.OrganisationHierarchyItem;
                    SessionManager.CurrentOrganisationHierarchy = model.OrganisationHierarchyItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = FixedResources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /OrganisationHierarchy/Edit with Exit button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitOrganisationHierarchy(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                SessionManager.CurrentOrganisationHierarchy = null;
                SessionManager.OrganisationHierarchyServiceVersion = null;

                return RedirectToAction("Search", "OrganisationHierarchy");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region Delete

        // POST: /OrganisationHierarchy/Edit with Delete button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult DeleteOrganisationHierarchy(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsDeleteConfirmed == "True")
            {
                //Set flags false
                SetFlagsFalse(model);
            
                model.IsDeleteConfirmed = "False";
				
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to delete the item
                    sc.DeleteOrganisationHierarchy(CurrentUser, CurrentUser, appID, "", model.OrganisationHierarchyItem.Code.ToString(), model.OrganisationHierarchyItem.RowIdentifier.ToString());

					// Close service communication
					sc.Close();
					
                    // Remove the current values from session
                    SessionManager.CurrentOrganisationHierarchy = null;
                    SessionManager.OrganisationHierarchyServiceVersion = null;

					// Redirect to the search screen
                    return RedirectToAction("Search", "OrganisationHierarchy");
                }
				catch (Exception e)
                {
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
                }
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_DELETECONFIRMATION;
                model.IsDeleteConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /OrganisationHierarchy/Edit with New button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewOrganisationHierarchy(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			SessionManager.OrganisationHierarchyCode = null;
            SessionManager.CurrentOrganisationHierarchy = null;
            SessionManager.OrganisationHierarchyServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "OrganisationHierarchy");
        }
		
		#endregion

		#region Search

        // GET: /OrganisationHierarchy/Search
        //This is called when first entering search OrganisationHierarchy screen or when paging
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			AdminServiceClient sc = new AdminServiceClient();
			
			// Create model
			OrganisationHierarchySearchVM model = new OrganisationHierarchySearchVM();
			
			try
			{
				OrganisationHierarchySearchVMDC response = sc.SearchOrganisationHierarchy(CurrentUser, CurrentUser, appID, "", null, page, PageSize, true);

				// Close service communication
				sc.Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<OrganisationHierarchySearchMatchDC>, List<OrganisationHierarchySearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = SessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				SessionManager.OrganisationHierarchyPageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /OrganisationHierarchy/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(OrganisationHierarchySearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					SessionManager.OrganisationHierarchyCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "OrganisationHierarchy", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(OrganisationHierarchyVM model)
        {
            model.IsDeleteConfirmed = "False";
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(OrganisationHierarchyVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private OrganisationHierarchyVM GetUpdatedModel()
        {
            OrganisationHierarchyVM model = new OrganisationHierarchyVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (SessionManager.CurrentOrganisationHierarchy != null)
            {
                model.OrganisationHierarchyItem = SessionManager.CurrentOrganisationHierarchy;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (SessionManager.CurrentOrganisationHierarchy != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.OrganisationHierarchyItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private OrganisationHierarchyVM ConvertOrganisationHierarchyDC(OrganisationHierarchyVMDC returnedObject)
        {
            OrganisationHierarchyVM model = new OrganisationHierarchyVM();
            
			// Map OrganisationHierarchy Item
			model.OrganisationHierarchyItem = Mapper.Map<OrganisationHierarchyDC, OrganisationHierarchyModel>(returnedObject.OrganisationHierarchyItem);
            
			// Map lookup data lists
			model.AncestorOrganisationList = Mapper.Map<IEnumerable<OrganisationDC>, List<OrganisationModel>>(returnedObject.AncestorOrganisationList);
			model.OrganisationList = Mapper.Map<IEnumerable<OrganisationDC>, List<OrganisationModel>>(returnedObject.OrganisationList);
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(OrganisationHierarchyVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            OrganisationHierarchyLookupListsCacheObject CachedLists = CacheManager.OrganisationHierarchyListCache;

			// Retrieve any cached lists to model
			model.AncestorOrganisationList = CachedLists.AncestorOrganisationList;
			model.OrganisationList = CachedLists.OrganisationList;
   
        }

        private void MergeNewValuesWithOriginal(OrganisationHierarchyModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            OrganisationHierarchyModel OriginalValuesFromSession = SessionManager.CurrentOrganisationHierarchy;

        }
		
		private void SetAccessContext(OrganisationHierarchyVM model)
        {
            //Decide on access context
            if (null == model.OrganisationHierarchyItem || model.OrganisationHierarchyItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = OrganisationHierarchyAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = OrganisationHierarchyAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(OrganisationHierarchyVM model)
        {
            //Compare the OrganisationHierarchy to the original session
            if (model.OrganisationHierarchyItem.PublicInstancePropertiesEqual(SessionManager.OrganisationHierarchyServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
