//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Framework.Management.ResourceLibrary;
using AutoMapper;
using Dwp.Adep.Framework.Management.Web.Helpers;
using Dwp.Adep.Framework.Management.Web.ViewModels;
using Dwp.Adep.Framework.Management.Web.Models;
using Dwp.Adep.Framework.Management.Web.AdminService;


namespace Dwp.Adep.Framework.Management.Web.Controllers
{
    public partial class OrganisationTypeController : BaseController
    {
		#region Edit
		
        // GET: /OrganisationType/Edit
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = SessionManager.OrganisationTypeCode;
			
            OrganisationTypeVM model = new OrganisationTypeVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.OrganisationTypeItem = new OrganisationTypeModel(){IsActive = true};
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to get OrganisationType item and any associated lookups    
                    OrganisationTypeVMDC returnedObject = sc.GetOrganisationType(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					sc.Close();

                    //Get view model from service
                    model = ConvertOrganisationTypeDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    SessionManager.OrganisationTypeServiceVersion = model.OrganisationTypeItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved OrganisationType to session
            SessionManager.CurrentOrganisationType = model.OrganisationTypeItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /OrganisationType/Edit with Create button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateOrganisationType(FormCollection collection)
        {
            return UpdateOrganisationType();
        }

        // POST: /OrganisationType/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveOrganisationType(FormCollection collection)
        {
            return UpdateOrganisationType();
        }

        //This method is shared between create and save
        private ActionResult UpdateOrganisationType()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    OrganisationTypeDC OrganisationTypeItem = Mapper.Map<OrganisationTypeDC>(model.OrganisationTypeItem);

					OrganisationTypeVMDC returnedObject = null;

                    if (null == model.OrganisationTypeItem.Code || model.OrganisationTypeItem.Code == Guid.Empty)
                    {
						// Call service to create new OrganisationType item
                        returnedObject = sc.CreateOrganisationType(CurrentUser, CurrentUser, appID, "", OrganisationTypeItem);
                    }
                    else
                    {
						// Call service to update OrganisationType item
                        returnedObject = sc.UpdateOrganisationType(CurrentUser, CurrentUser, appID, "", OrganisationTypeItem);
                    }

					// Close service communication
					sc.Close();
					
					// Retrieve item returned by service
                    var createdOrganisationType = returnedObject.OrganisationTypeItem;

					// Map data contract to model
                    model.OrganisationTypeItem = Mapper.Map<OrganisationTypeModel>(createdOrganisationType);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = OrganisationTypeAccessContext.Edit;

					// Save version of item returned by service into session
                    SessionManager.OrganisationTypeServiceVersion = model.OrganisationTypeItem;
                    SessionManager.CurrentOrganisationType = model.OrganisationTypeItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = FixedResources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /OrganisationType/Edit with Exit button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitOrganisationType(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                SessionManager.CurrentOrganisationType = null;
                SessionManager.OrganisationTypeServiceVersion = null;

                return RedirectToAction("Search", "OrganisationType");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /OrganisationType/Edit with New button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewOrganisationType(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			SessionManager.OrganisationTypeCode = null;
            SessionManager.CurrentOrganisationType = null;
            SessionManager.OrganisationTypeServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "OrganisationType");
        }
		
		#endregion

		#region Search

        // GET: /OrganisationType/Search
        //This is called when first entering search OrganisationType screen or when paging
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			AdminServiceClient sc = new AdminServiceClient();
			
			// Create model
			OrganisationTypeSearchVM model = new OrganisationTypeSearchVM();
			
			try
			{
				OrganisationTypeSearchVMDC response = sc.SearchOrganisationType(CurrentUser, CurrentUser, appID, "", null, page, PageSize, true);

				// Close service communication
				sc.Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<OrganisationTypeSearchMatchDC>, List<OrganisationTypeSearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = SessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				SessionManager.OrganisationTypePageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /OrganisationType/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(OrganisationTypeSearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					SessionManager.OrganisationTypeCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "OrganisationType", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(OrganisationTypeVM model)
        {
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(OrganisationTypeVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private OrganisationTypeVM GetUpdatedModel()
        {
            OrganisationTypeVM model = new OrganisationTypeVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (SessionManager.CurrentOrganisationType != null)
            {
                model.OrganisationTypeItem = SessionManager.CurrentOrganisationType;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (SessionManager.CurrentOrganisationType != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.OrganisationTypeItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private OrganisationTypeVM ConvertOrganisationTypeDC(OrganisationTypeVMDC returnedObject)
        {
            OrganisationTypeVM model = new OrganisationTypeVM();
            
			// Map OrganisationType Item
			model.OrganisationTypeItem = Mapper.Map<OrganisationTypeDC, OrganisationTypeModel>(returnedObject.OrganisationTypeItem);
            
			// Map lookup data lists
			model.OrganisationTypeGroupList = Mapper.Map<IEnumerable<OrganisationTypeGroupDC>, List<OrganisationTypeGroupModel>>(returnedObject.OrganisationTypeGroupList);
			model.ParentOrganisationTypeList = Mapper.Map<IEnumerable<OrganisationTypeDC>, List<OrganisationTypeModel>>(returnedObject.ParentOrganisationTypeList);
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(OrganisationTypeVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            OrganisationTypeLookupListsCacheObject CachedLists = CacheManager.OrganisationTypeListCache;

			// Retrieve any cached lists to model
			model.OrganisationTypeGroupList = CachedLists.OrganisationTypeGroupList;
			model.ParentOrganisationTypeList = CachedLists.ParentOrganisationTypeList;
   
        }

        private void MergeNewValuesWithOriginal(OrganisationTypeModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            OrganisationTypeModel OriginalValuesFromSession = SessionManager.CurrentOrganisationType;

        }
		
		private void SetAccessContext(OrganisationTypeVM model)
        {
            //Decide on access context
            if (null == model.OrganisationTypeItem || model.OrganisationTypeItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = OrganisationTypeAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = OrganisationTypeAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(OrganisationTypeVM model)
        {
            //Compare the OrganisationType to the original session
            if (model.OrganisationTypeItem.PublicInstancePropertiesEqual(SessionManager.OrganisationTypeServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
