//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Framework.Management.ResourceLibrary;
using AutoMapper;
using Dwp.Adep.Framework.Management.Web.Helpers;
using Dwp.Adep.Framework.Management.Web.ViewModels;
using Dwp.Adep.Framework.Management.Web.Models;
using Dwp.Adep.Framework.Management.Web.AdminService;


namespace Dwp.Adep.Framework.Management.Web.Controllers
{
    public partial class StaffOfficesController : BaseController
    {
		#region Edit
		
        // GET: /StaffOffices/Edit
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = SessionManager.StaffOfficesCode;
			
            StaffOfficesVM model = new StaffOfficesVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.StaffOfficesItem = new StaffOfficesModel();
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to get StaffOffices item and any associated lookups    
                    StaffOfficesVMDC returnedObject = sc.GetStaffOffices(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					sc.Close();

                    //Get view model from service
                    model = ConvertStaffOfficesDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    SessionManager.StaffOfficesServiceVersion = model.StaffOfficesItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved StaffOffices to session
            SessionManager.CurrentStaffOffices = model.StaffOfficesItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /StaffOffices/Edit with Create button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateStaffOffices(FormCollection collection)
        {
            return UpdateStaffOffices();
        }

        // POST: /StaffOffices/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveStaffOffices(FormCollection collection)
        {
            return UpdateStaffOffices();
        }

        //This method is shared between create and save
        private ActionResult UpdateStaffOffices()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    StaffOfficesDC StaffOfficesItem = Mapper.Map<StaffOfficesDC>(model.StaffOfficesItem);

					StaffOfficesVMDC returnedObject = null;

                    if (null == model.StaffOfficesItem.Code || model.StaffOfficesItem.Code == Guid.Empty)
                    {
						// Call service to create new StaffOffices item
                        returnedObject = sc.CreateStaffOffices(CurrentUser, CurrentUser, appID, "", StaffOfficesItem);
                    }
                    else
                    {
						// Call service to update StaffOffices item
                        returnedObject = sc.UpdateStaffOffices(CurrentUser, CurrentUser, appID, "", StaffOfficesItem);
                    }

					// Close service communication
					sc.Close();
					
					// Retrieve item returned by service
                    var createdStaffOffices = returnedObject.StaffOfficesItem;

					// Map data contract to model
                    model.StaffOfficesItem = Mapper.Map<StaffOfficesModel>(createdStaffOffices);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = StaffOfficesAccessContext.Edit;

					// Save version of item returned by service into session
                    SessionManager.StaffOfficesServiceVersion = model.StaffOfficesItem;
                    SessionManager.CurrentStaffOffices = model.StaffOfficesItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = FixedResources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /StaffOffices/Edit with Exit button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitStaffOffices(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                SessionManager.CurrentStaffOffices = null;
                SessionManager.StaffOfficesServiceVersion = null;

                return RedirectToAction("Search", "StaffOffices");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /StaffOffices/Edit with New button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewStaffOffices(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			SessionManager.StaffOfficesCode = null;
            SessionManager.CurrentStaffOffices = null;
            SessionManager.StaffOfficesServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "StaffOffices");
        }
		
		#endregion

		#region Search

        // GET: /StaffOffices/Search
        //This is called when first entering search StaffOffices screen or when paging
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			AdminServiceClient sc = new AdminServiceClient();
			
			// Create model
			StaffOfficesSearchVM model = new StaffOfficesSearchVM();
			
			try
			{
				StaffOfficesSearchVMDC response = sc.SearchStaffOffices(CurrentUser, CurrentUser, appID, "", null, page, PageSize);

				// Close service communication
				sc.Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<StaffOfficesSearchMatchDC>, List<StaffOfficesSearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = SessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				SessionManager.StaffOfficesPageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /StaffOffices/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(StaffOfficesSearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					SessionManager.StaffOfficesCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "StaffOffices", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(StaffOfficesVM model)
        {
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(StaffOfficesVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private StaffOfficesVM GetUpdatedModel()
        {
            StaffOfficesVM model = new StaffOfficesVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (SessionManager.CurrentStaffOffices != null)
            {
                model.StaffOfficesItem = SessionManager.CurrentStaffOffices;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (SessionManager.CurrentStaffOffices != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.StaffOfficesItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private StaffOfficesVM ConvertStaffOfficesDC(StaffOfficesVMDC returnedObject)
        {
            StaffOfficesVM model = new StaffOfficesVM();
            
			// Map StaffOffices Item
			model.StaffOfficesItem = Mapper.Map<StaffOfficesDC, StaffOfficesModel>(returnedObject.StaffOfficesItem);
            
			// Map lookup data lists
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(StaffOfficesVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            StaffOfficesLookupListsCacheObject CachedLists = CacheManager.StaffOfficesListCache;

			// Retrieve any cached lists to model
   
        }

        private void MergeNewValuesWithOriginal(StaffOfficesModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            StaffOfficesModel OriginalValuesFromSession = SessionManager.CurrentStaffOffices;

        }
		
		private void SetAccessContext(StaffOfficesVM model)
        {
            //Decide on access context
            if (null == model.StaffOfficesItem || model.StaffOfficesItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = StaffOfficesAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = StaffOfficesAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(StaffOfficesVM model)
        {
            //Compare the StaffOffices to the original session
            if (model.StaffOfficesItem.PublicInstancePropertiesEqual(SessionManager.StaffOfficesServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
