//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Linq;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ServiceModel;
using Dwp.Adep.Framework.Management.ResourceLibrary;
using AutoMapper;
using Dwp.Adep.Framework.Management.Web.Helpers;
using Dwp.Adep.Framework.Management.Web.ViewModels;
using Dwp.Adep.Framework.Management.Web.Models;
using Dwp.Adep.Framework.Management.Web.AdminService;


namespace Dwp.Adep.Framework.Management.Web.Controllers
{
    public partial class TitleController : BaseController
    {
		#region Edit
		
        // GET: /Title/Edit
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Edit()
        {
			// Retrieve ID from session
			string code = SessionManager.TitleCode;
			
            TitleVM model = new TitleVM();
			
            // Not from staff or error
            if (String.IsNullOrEmpty(code))
            {
                //If session has lists then use them
                RepopulateListsFromCacheSession(model);

                //Assume we are in create mode as no code passed
                model.TitleItem = new TitleModel();                              
            }
            //if we have been passed a code then assume we are in edit situation and we need to retrieve from the database.
            else
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to get Title item and any associated lookups    
                    TitleVMDC returnedObject = sc.GetTitle(CurrentUser, CurrentUser, appID, "", code);

					// Close service communication
					sc.Close();

                    //Get view model from service
                    model = ConvertTitleDC(returnedObject);

                    ResolveFieldCodesToFieldNamesUsingLists(model);

                    //Store the service version
                    SessionManager.TitleServiceVersion = model.TitleItem;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            //Adds current retrieved Title to session
            SessionManager.CurrentTitle = model.TitleItem;
            SetAccessContext(model);
            
            return View(model);
        }    
		
		#endregion
		
		#region Create/Update

        // POST: /Title/Edit with Create button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult CreateTitle(FormCollection collection)
        {
            return UpdateTitle();
        }

        // POST: /Title/Edit with Save button submitting
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult SaveTitle(FormCollection collection)
        {
            return UpdateTitle();
        }

        //This method is shared between create and save
        private ActionResult UpdateTitle()
        {
			// Get the updated model
            var model = GetUpdatedModel();

			// Test to see if there are any errors
            var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors[0].ErrorMessage })
                    .ToArray();
            
			//Set flags false
            SetFlagsFalse(model);
			
			// Test to see if the model has validated correctly
            if (ModelState.IsValid)
            {
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                //Attempt update
                try
                {
                    // Map model to data contract
                    TitleDC TitleItem = Mapper.Map<TitleDC>(model.TitleItem);

					TitleVMDC returnedObject = null;

                    if (null == model.TitleItem.Code || model.TitleItem.Code == Guid.Empty)
                    {
						// Call service to create new Title item
                        returnedObject = sc.CreateTitle(CurrentUser, CurrentUser, appID, "", TitleItem);
                    }
                    else
                    {
						// Call service to update Title item
                        returnedObject = sc.UpdateTitle(CurrentUser, CurrentUser, appID, "", TitleItem);
                    }

					// Close service communication
					sc.Close();
					
					// Retrieve item returned by service
                    var createdTitle = returnedObject.TitleItem;

					// Map data contract to model
                    model.TitleItem = Mapper.Map<TitleModel>(createdTitle);
					
                    //After creation some of the fields are display only so we need the resolved look up nmames
                    ResolveFieldCodesToFieldNamesUsingLists(model);

					// Set access context to Edit mode
                    model.AccessContext = TitleAccessContext.Edit;

					// Save version of item returned by service into session
                    SessionManager.TitleServiceVersion = model.TitleItem;
                    SessionManager.CurrentTitle = model.TitleItem;
                    
                    // Remove the state from the model as these are being populated by the controller and the HTML helpers are being populated with
					// the POSTED values and not the changed ones.
                    ModelState.Clear();
                    model.Message = FixedResources.MESSAGE_UPDATE_SUCCEEDED;
                }
				catch (Exception e)
				{
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
				}
            }

            return View(model);
        }

        #endregion
		
		#region Exit

        // POST: /Title/Edit with Exit button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult ExitTitle(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsExitConfirmed == "True" || !model.IsViewDirty)
            {
                //Set flags false
                SetFlagsFalse(model);

                model.IsExitConfirmed = "False";
                
                //remove the current values from session
                SessionManager.CurrentTitle = null;
                SessionManager.TitleServiceVersion = null;

                return RedirectToAction("Search", "Title");
                
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_EXITCONFIRMATION;
                model.IsExitConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region Delete

        // POST: /Title/Edit with Delete button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamEdit(Prefix = "Edit::")]
        [HttpPost]
        public ActionResult DeleteTitle(FormCollection collection)
        {
            var model = GetUpdatedModel();
            if (model.IsDeleteConfirmed == "True")
            {
                //Set flags false
                SetFlagsFalse(model);
            
                model.IsDeleteConfirmed = "False";
				
				// Create service instance
				AdminServiceClient sc = new AdminServiceClient();
				
                try
                {
					// Call service to delete the item
                    sc.DeleteTitle(CurrentUser, CurrentUser, appID, "", model.TitleItem.Code.ToString(), model.TitleItem.RowIdentifier.ToString());

					// Close service communication
					sc.Close();
					
                    // Remove the current values from session
                    SessionManager.CurrentTitle = null;
                    SessionManager.TitleServiceVersion = null;

					// Redirect to the search screen
                    return RedirectToAction("Search", "Title");
                }
				catch (Exception e)
                {
					// Handle the exception
					string message = ExceptionManager.HandleException(e, sc);
					model.Message = message;
					
					return View(model);
                }
            }
            else
            {
                //Set flags false
                SetFlagsFalse(model);
                model.Message = FixedResources.MESSAGE_DELETECONFIRMATION;
                model.IsDeleteConfirmed = "True";
            }
            
            return View(model);
        }
		
		#endregion
		
		#region New

        // POST: /Title/Edit with New button submitting
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        [HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult NewTitle(FormCollection collection)
        {
            var model = GetUpdatedModel();
            //Set flags false
            SetFlagsFalse(model);
            
            //Clear Down Session
			SessionManager.TitleCode = null;
            SessionManager.CurrentTitle = null;
            SessionManager.TitleServiceVersion = null;
            
            //Go to the Edit Screen
            return RedirectToAction("Edit", "Title");
        }
		
		#endregion

		#region Search

        // GET: /Title/Search
        //This is called when first entering search Title screen or when paging
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
        public ActionResult Search(int page = 1)
        {   
			// Create service instance
			AdminServiceClient sc = new AdminServiceClient();
			
			// Create model
			TitleSearchVM model = new TitleSearchVM();
			
			try
			{
				TitleSearchVMDC response = sc.SearchTitle(CurrentUser, CurrentUser, appID, "", null, page, PageSize, true);

				// Close service communication
				sc.Close();

				//Map response back to view model
				model.MatchList = Mapper.Map<IEnumerable<TitleSearchMatchDC>, List<TitleSearchMatchModel>>(response.MatchList);

				// Set paging values
				model.TotalRows = response.RecordCount;
				model.PageSize = SessionManager.PageSize;
				model.PageNumber = page;
				
				// Store the page number we were on
				SessionManager.TitlePageNumber = model.PageNumber;
	        
				return View(model);
			}
			catch (Exception e)
			{
				// Handle the exception
				string message = ExceptionManager.HandleException(e, sc);
				model.Message = message;
				
				return View(model);
			}

        }

        // POST: /Title/Search
        //This is called when clicking search button
		[CustomAuthorize(Roles = FrameworkRoles.ADMIN)]
		[HttpParamSearch(Prefix = "Search::")]
        [HttpPost]
        public ActionResult SearchPost(TitleSearchVM model, int page = 1)
        {
		
			// Iterate through form keys
            foreach (string Key in Request.Form.Keys)
            {
				// Test if Select button was clicked...
                if (Key.StartsWith("Search::SearchPost_"))
                {
					// Retrieve ID for entity which was selected
                    Guid Value = Guid.Parse(Key.Substring(19));
									
					// Store ID for Edit screen
					SessionManager.TitleCode = Value.ToString();
					
					// Call out to Edit screen
                    return RedirectToAction("Edit", "Title", new { code = Value });

                }
            }

            // Return to the Screen
            return View(model);
        }

        #endregion
		
		#region Private methods
		
        private void SetFlagsFalse(TitleVM model)
        {
            model.IsDeleteConfirmed = "False";
            model.IsExitConfirmed = "False";
            model.IsNewConfirmed = "False";

            //Stop the binder resetting the posted values
            ModelState.Remove("IsDeleteConfirmed");
            ModelState.Remove("IsExitConfirmed");
            ModelState.Remove("IsNewConfirmed");
        }

        private void ResolveFieldCodesToFieldNamesUsingLists(TitleVM model)
        {
			//TODO:
        }

        /// <summary>
        /// Private method to merge in the model 
        /// </summary>
        /// <returns></returns>
        private TitleVM GetUpdatedModel()
        {
            TitleVM model = new TitleVM();
            RepopulateListsFromCacheSession(model);
            model.Message = "";

            if (SessionManager.CurrentTitle != null)
            {
                model.TitleItem = SessionManager.CurrentTitle;
            }

            //***************************************NEED WHITE LIST ---- BLACK LIST ------ TO PREVENT OVERPOSTING **************************
            bool result = TryUpdateModel(model);//This also validates and sets ModelState
            //*******************************************************************************************************************************
            if (SessionManager.CurrentTitle != null)
            {
                //*****************************************PREVENT OVER POSTING ATTACKS******************************************************
                //Get the values for read only fields from session
                MergeNewValuesWithOriginal(model.TitleItem);
                //***************************************************************************************************************************
            }

            SetAccessContext(model);

            return model;
        }
		
        private TitleVM ConvertTitleDC(TitleVMDC returnedObject)
        {
            TitleVM model = new TitleVM();
            
			// Map Title Item
			model.TitleItem = Mapper.Map<TitleDC, TitleModel>(returnedObject.TitleItem);
            
			// Map lookup data lists
        
            return model;
        }
		
		private void RepopulateListsFromCacheSession(TitleVM model)
        {
			// Populate cached lists if they are empty. Will invoke service call
            TitleLookupListsCacheObject CachedLists = CacheManager.TitleListCache;

			// Retrieve any cached lists to model
   
        }

        private void MergeNewValuesWithOriginal(TitleModel modelFromView)
        {
            //***************************The values that are display only will not be posted back so need to get them from session**************************

            TitleModel OriginalValuesFromSession = SessionManager.CurrentTitle;

        }
		
		private void SetAccessContext(TitleVM model)
        {
            //Decide on access context
            if (null == model.TitleItem || model.TitleItem.Code == Guid.Empty)
            {
				// Create context
                model.AccessContext = TitleAccessContext.Create;
            }
            else
            {
				// Edit context
                model.AccessContext = TitleAccessContext.Edit;
            }
        }
		
		private void DetermineIsDirty(TitleVM model)
        {
            //Compare the Title to the original session
            if (model.TitleItem.PublicInstancePropertiesEqual(SessionManager.TitleServiceVersion, "RowIdentifier"))
            {
                model.IsViewDirty = false;
            }
            else
            {
                model.IsViewDirty = true;
            }

        }
        #endregion
       
    }
}
