//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using AutoMapper;
using Dwp.Adep.Framework.Management.DataServices.Models;
using Dwp.Adep.Framework.Management.WebServices.DataContracts;

namespace Dwp.Adep.Framework.Management.WebServices.ServiceContracts
{
    
    partial class AdminService
    {
        partial void DefineTypeMappings()
        {
    
                Mapper.CreateMap<Application, ApplicationDC>();
                Mapper.CreateMap<ApplicationDC, Application>();
    			Mapper.CreateMap<Application, ApplicationSearchMatchDC>();
    
                Mapper.CreateMap<ApplicationAttribute, ApplicationAttributeDC>();
                Mapper.CreateMap<ApplicationAttributeDC, ApplicationAttribute>();
    			Mapper.CreateMap<ApplicationAttribute, ApplicationAttributeSearchMatchDC>();
    
                Mapper.CreateMap<Audit, AuditDC>();
                Mapper.CreateMap<AuditDC, Audit>();
    			Mapper.CreateMap<Audit, AuditSearchMatchDC>();
    
                Mapper.CreateMap<Country, CountryDC>();
                Mapper.CreateMap<CountryDC, Country>();
    			Mapper.CreateMap<Country, CountrySearchMatchDC>();
    
                Mapper.CreateMap<Grade, GradeDC>();
                Mapper.CreateMap<GradeDC, Grade>();
    			Mapper.CreateMap<Grade, GradeSearchMatchDC>();
    
                Mapper.CreateMap<Holiday, HolidayDC>();
                Mapper.CreateMap<HolidayDC, Holiday>();
    			Mapper.CreateMap<Holiday, HolidaySearchMatchDC>();
    
                Mapper.CreateMap<NonStandardHoliday, NonStandardHolidayDC>();
                Mapper.CreateMap<NonStandardHolidayDC, NonStandardHoliday>();
    			Mapper.CreateMap<NonStandardHoliday, NonStandardHolidaySearchMatchDC>();
    
                Mapper.CreateMap<Organisation, OrganisationDC>();
                Mapper.CreateMap<OrganisationDC, Organisation>();
    			Mapper.CreateMap<Organisation, OrganisationSearchMatchDC>();
    
                Mapper.CreateMap<OrganisationType, OrganisationTypeDC>();
                Mapper.CreateMap<OrganisationTypeDC, OrganisationType>();
    			Mapper.CreateMap<OrganisationType, OrganisationTypeSearchMatchDC>();
    
                Mapper.CreateMap<OrganisationTypeGroup, OrganisationTypeGroupDC>();
                Mapper.CreateMap<OrganisationTypeGroupDC, OrganisationTypeGroup>();
    			Mapper.CreateMap<OrganisationTypeGroup, OrganisationTypeGroupSearchMatchDC>();
    
                Mapper.CreateMap<Staff, StaffDC>();
                Mapper.CreateMap<StaffDC, Staff>();
    			Mapper.CreateMap<Staff, StaffSearchMatchDC>();
    
                Mapper.CreateMap<StaffAttributes, StaffAttributesDC>();
                Mapper.CreateMap<StaffAttributesDC, StaffAttributes>();
    			Mapper.CreateMap<StaffAttributes, StaffAttributesSearchMatchDC>();
    
                Mapper.CreateMap<StaffDetails, StaffDetailsDC>();
                Mapper.CreateMap<StaffDetailsDC, StaffDetails>();
    			Mapper.CreateMap<StaffDetails, StaffDetailsSearchMatchDC>();
    
                Mapper.CreateMap<StaffOffices, StaffOfficesDC>();
                Mapper.CreateMap<StaffOfficesDC, StaffOffices>();
    			Mapper.CreateMap<StaffOffices, StaffOfficesSearchMatchDC>();
    
                Mapper.CreateMap<StaffOrganisation, StaffOrganisationDC>();
                Mapper.CreateMap<StaffOrganisationDC, StaffOrganisation>();
    			Mapper.CreateMap<StaffOrganisation, StaffOrganisationSearchMatchDC>();
    	}
    }
}
