//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ServiceModel;
using AutoMapper;
using Dwp.Adep.Framework.Management.WebServices.DataContracts;
using Dwp.Adep.Framework.Management.WebServices.Exceptions;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;
using Dwp.Adep.Framework.Management.WebServices.ServiceContracts;

namespace Dwp.Adep.Framework.Management.WebServices.ServiceContracts
{
    public partial class AdminService
    {
        #region CRUD Behaviour for Validator
    
            #region Create
    
            public void CreateValidator(string userName, string currentUserName, string appID, string overrideID, ValidatorDC dc)
            {
                IUnitOfWork uow = new UnitOfWork();
    
                Repository<Validator> dataRepository = new Repository<Validator>(uow.ObjectContext);
    
                CreateValidator(userName, currentUserName, appID, overrideID, dc, dataRepository, uow);
            }
    
            public void CreateValidator(string userName, string currentUserName, string appID, string overrideID, ValidatorDC dc, IRepository<Validator> dataRepository, IUnitOfWork uow)
            {
                try
                {
                    using (uow)
                    {
                        Validator destination = Mapper.Map<ValidatorDC, Validator>(dc);
    
                        dataRepository.Add(destination);
    
                        uow.Commit();
                    }
                }
                catch (Exception e)
                {
                    //Prevent exception from propogating across the service interface
                    ExceptionManager.ShieldException(e);
                }
            }
    
            #endregion
    
            #region GetValidator
    
            public ValidatorDC GetValidator(string userName, string currentUserName, string appID, string overrideID, string code)
            {
                IUnitOfWork uow = new UnitOfWork();
    
                Repository<Validator> dataRepository = new Repository<Validator>(uow.ObjectContext);
    
                return GetValidator(userName, currentUserName, appID, overrideID, code, dataRepository, uow);
            }
    
            public ValidatorDC GetValidator(string userName, string currentUserName, string appID, string overrideID, string code, IRepository<Validator> dataRepository, IUnitOfWork uow)
            {
                try
                {
                    using (uow)
                    {
                        Guid codeGuid = Guid.Parse(code);
    
                        Validator dataEntity = dataRepository.Single(x => x.Code == codeGuid);
    
                        ValidatorDC destination = Mapper.Map<Validator, ValidatorDC>(dataEntity);
    
                        return destination;
                    }
                }
                catch (Exception e)
                {
                    //Prevent exception from propogating across the service interface
                    ExceptionManager.ShieldException(e);
    
                    return null;
                }
            }
    
            public List<ValidatorDC> GetAllValidator(string userName, string currentUserName, string appID, string overrideID)
            {
                IUnitOfWork uow = new UnitOfWork();
    
                Repository<Validator> dataRepository = new Repository<Validator>(uow.ObjectContext);
    
                return GetAllValidator(userName, currentUserName, appID, overrideID, dataRepository, uow);
            }
    
            public List<ValidatorDC> GetAllValidator(string userName, string currentUserName, string appID, string overrideID, IRepository<Validator> dataRepository, IUnitOfWork uow)
            {
                try
                {
                    using (uow)
                    {
                        IEnumerable<Validator> dataEntities = dataRepository.GetAll();
    
                        List<ValidatorDC> destinations = Mapper.Map<IEnumerable<Validator>, List<ValidatorDC>>(dataEntities);
    
                        return destinations;
                    }
                }
                catch (Exception e)
                {
                    //Prevent exception from propogating across the service interface
                    ExceptionManager.ShieldException(e);
    
                    return null;
                }
            }
    
            #endregion
    
            #region Update
    
            public void UpdateValidator(string userName, string currentUserName, string appID, string overrideID, ValidatorDC dc)
            {
                IUnitOfWork uow = new UnitOfWork();
    
                IRepository<Validator> dataRepository = new Repository<Validator>(uow.ObjectContext);
    
                UpdateValidator(userName, currentUserName, appID, overrideID, dc, dataRepository, uow);
            }
    
            public void UpdateValidator(string userName, string currentUserName, string appID, string overrideID, ValidatorDC dc, IRepository<Validator> dataRepository, IUnitOfWork uow)
            {
                try
                {
                    using (uow)
                    {
                        Validator destination = Mapper.Map<ValidatorDC, Validator>(dc);
    
                        dataRepository.Update(destination);
    
                        uow.Commit();
                    }
                }
                catch (Exception e)
                {
                    //Prevent exception from propogating across the service interface
                    ExceptionManager.ShieldException(e);
                }
            }
    
            #endregion
    
            #region Delete
    
            public void DeleteValidator(string userName, string currentUserName, string appID, string overrideID, string code, string lockID)
            {
                IUnitOfWork uow = new UnitOfWork();
    
                IRepository<Validator> dataRepository = new Repository<Validator>(uow.ObjectContext);
    
                DeleteValidator(userName, currentUserName, appID, overrideID, code, lockID, dataRepository, uow);
            }
    
            public void DeleteValidator(string userName, string currentUserName, string appID, string overrideID, string code, string lockID, IRepository<Validator> dataRepository, IUnitOfWork uow)
            {
                try
                {
                    using (uow)
                    {
                        Guid codeGuid = Guid.Parse(code);
    
                        Validator dataEntity = dataRepository.Single(x => x.Code == codeGuid);
    
                        dataRepository.Delete(dataEntity);
    
                        uow.Commit();
                    }
                }
                catch (Exception e)
                {
                    //Prevent exception from propogating across the service interface
                    ExceptionManager.ShieldException(e);
                }
            }
    
            #endregion

        #endregion
    }
}
