//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ServiceModel;
using Dwp.Adep.Framework.Management.WebServices.DataContracts;

namespace Dwp.Adep.Framework.Management.WebServices.ServiceContracts
{
    public partial interface IAdminService
    {
        #region CRUD Behaviour for Command
    
    	[OperationContract]
    	void CreateCommand(string userName, string currentUserName, string appID, string overrideID, CommandDC dc);
    
    	[OperationContract]
    	CommandVMDC GetCommand(string userName, string currentUserName, string appID, string overrideID, string code);
    
    	[OperationContract]
    	List<CommandDC> GetAllCommand(string userName, string currentUserName, string appID, string overrideID, bool includeInActive);
    
    	[OperationContract]
    	CommandSearchMatchResultsDC SearchCommand(string userName, string currentUserName, string appID, string overrideID, CommandSearchCriteriaDC searchCriteria, int page, int pageSize, bool includeInActive);
    
    	[OperationContract]
    	void UpdateCommand(string userName, string currentUserName, string appID, string overrideID, CommandDC dc);
    
    	[OperationContract]
    	void DeleteCommand(string userName, string currentUserName, string appID, string overrideID, string dcCode, string lockID);

        #endregion
    }
}
