//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ServiceModel;
using Dwp.Adep.Framework.Management.WebServices.DataContracts;

namespace Dwp.Adep.Framework.Management.WebServices.ServiceContracts
{
    public partial interface IAdminService
    {
        #region CRUD Behaviour for ImportStaff
    
    	[OperationContract]
    	void CreateImportStaff(string userName, string currentUserName, string appID, string overrideID, ImportStaffDC dc);
    
    	[OperationContract]
    	ImportStaffDC GetImportStaff(string userName, string currentUserName, string appID, string overrideID, string code);
    
    	[OperationContract]
    	List<ImportStaffDC> GetAllImportStaff(string userName, string currentUserName, string appID, string overrideID);
    
    	[OperationContract]
    	void UpdateImportStaff(string userName, string currentUserName, string appID, string overrideID, ImportStaffDC dc);
    
    	[OperationContract]
    	void DeleteImportStaff(string userName, string currentUserName, string appID, string overrideID, string dcCode, string lockID);

        #endregion
    }
}
