//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(BenefitModel.BenefitModelMetadata))]
    public partial class BenefitModel : IBenefitModel
    {
    	public partial class BenefitModelMetadata
    	{
    		[Key]
    		[Required]
    		[Display(Name="LABEL_BENEFIT_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[StringLength(50)]
    		[Display(Name="LABEL_BENEFIT_BENEFIT1", ResourceType=typeof(Resources))]
    		public string Benefit1 {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_BENEFIT_ISACTIVE", ResourceType=typeof(Resources))]
    		public bool IsActive {get; set;}
    
        }
    }
}
