//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(CountryModel.CountryModelMetadata))]
    public partial class CountryModel : ICountryModel
    {
    	public partial class CountryModelMetadata
    	{
    		[Key]
    		[Required]
    		[Display(Name="LABEL_COUNTRY_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[StringLength(60)]
    		[Display(Name="LABEL_COUNTRY_DESCRIPTION", ResourceType=typeof(Resources))]
    		public string Description {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_COUNTRY_ISFROZENRATE", ResourceType=typeof(Resources))]
    		public bool IsFrozenRate {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_COUNTRY_ISEC", ResourceType=typeof(Resources))]
    		public bool IsEC {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_COUNTRY_ISRA", ResourceType=typeof(Resources))]
    		public bool IsRA {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_COUNTRY_ISANZAC", ResourceType=typeof(Resources))]
    		public bool IsANZAC {get; set;}
    
      		[StringLength(50)]
    		[Display(Name="LABEL_COUNTRY_NATIONALITY", ResourceType=typeof(Resources))]
    		public string Nationality {get; set;}
    
      		[StringLength(4)]
    		[Display(Name="LABEL_COUNTRY_COUNTRYCODE", ResourceType=typeof(Resources))]
    		public string CountryCode {get; set;}
    
      		[Display(Name="LABEL_COUNTRY_NOTES", ResourceType=typeof(Resources))]
    		public string Notes {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_COUNTRY_ISACTIVE", ResourceType=typeof(Resources))]
    		public bool IsActive {get; set;}
    
        }
    }
}
