//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(ErrorSubChoiceModel.ErrorSubChoiceModelMetadata))]
    public partial class ErrorSubChoiceModel : IErrorSubChoiceModel
    {
    	public partial class ErrorSubChoiceModelMetadata
    	{
    		[Key]
    		[Required]
    		[Display(Name="LABEL_ERRORSUBCHOICE_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_ERRORSUBCHOICE_ERRORCHOICECODE", ResourceType=typeof(Resources))]
    		public System.Guid ErrorChoiceCode {get; set;}
    
      		[StringLength(130)]
    		[Display(Name="LABEL_ERRORSUBCHOICE_DESCRIPTION", ResourceType=typeof(Resources))]
    		public string Description {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_ERRORSUBCHOICE_ISACTIVE", ResourceType=typeof(Resources))]
    		public bool IsActive {get; set;}
    
        }
    }
}
