//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    public partial class ImportStaffModel
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get { return _code; }
            set { _code = value; }
        }
        private System.Guid _code;
    
        public virtual string StaffNumber
        {
            get { return _staffNumber; }
            set { _staffNumber = value; }
        }
        private string _staffNumber;
    
        public virtual string LastName
        {
            get { return _lastName; }
            set { _lastName = value; }
        }
        private string _lastName;
    
        public virtual string FirstName
        {
            get { return _firstName; }
            set { _firstName = value; }
        }
        private string _firstName;
    
        public virtual string NetworkLastName
        {
            get { return _networkLastName; }
            set { _networkLastName = value; }
        }
        private string _networkLastName;
    
        public virtual string NetworkFirstName
        {
            get { return _networkFirstName; }
            set { _networkFirstName = value; }
        }
        private string _networkFirstName;
    
        public virtual Nullable<int> GradeID
        {
            get { return _gradeID; }
            set { _gradeID = value; }
        }
        private Nullable<int> _gradeID;
    
        public virtual Nullable<int> TeamID
        {
            get { return _teamID; }
            set { _teamID = value; }
        }
        private Nullable<int> _teamID;
    
        public virtual Nullable<int> CommandID
        {
            get { return _commandID; }
            set { _commandID = value; }
        }
        private Nullable<int> _commandID;
    
        public virtual Nullable<int> LocationID
        {
            get { return _locationID; }
            set { _locationID = value; }
        }
        private Nullable<int> _locationID;
    
        public virtual bool NonIPC
        {
            get { return _nonIPC; }
            set { _nonIPC = value; }
        }
        private bool _nonIPC;
    
        public virtual Nullable<System.DateTime> LeftIPC
        {
            get { return _leftIPC; }
            set { _leftIPC = value; }
        }
        private Nullable<System.DateTime> _leftIPC;
    
        public virtual byte[] RowIdentifier
        {
            get { return _rowIdentifier; }
            set { _rowIdentifier = value; }
        }
        private byte[] _rowIdentifier;

        #endregion
    }
}
