//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(OrganisationModel.OrganisationModelMetadata))]
    public partial class OrganisationModel : IOrganisationModel
    {
    	public partial class OrganisationModelMetadata
    	{
    		[Key]
    		[Required]
    		[Display(Name="LABEL_ORGANISATION_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_ORGANISATION_ID", ResourceType=typeof(Resources))]
    		public int ID {get; set;}
    
      		[Required]
    		[StringLength(1000)]
    		[Display(Name="LABEL_ORGANISATION_NAME", ResourceType=typeof(Resources))]
    		public string Name {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_ORGANISATION_ORGANISATIONTYPECODE", ResourceType=typeof(Resources))]
    		public System.Guid OrganisationTypeCode {get; set;}
    
      		[StringLength(35)]
    		[Display(Name="LABEL_ORGANISATION_HEO", ResourceType=typeof(Resources))]
    		public string HEO {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_ORGANISATION_DATEDELETED", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateDeleted {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_ORGANISATION_ISACTIVE", ResourceType=typeof(Resources))]
    		public bool IsActive {get; set;}
    
        }
    }
}
