//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(SecurityCheckModel.SecurityCheckModelMetadata))]
    public partial class SecurityCheckModel : ISecurityCheckModel
    {
    	public partial class SecurityCheckModelMetadata
    	{
    		[Key]
    		[Required]
    		[Display(Name="LABEL_SECURITYCHECK_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_SECURITYCHECK_CHECKID", ResourceType=typeof(Resources))]
    		public int CheckID {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_SEF_ID", ResourceType=typeof(Resources))]
    		public Nullable<int> SEF_ID {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATERAISED", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateRaised {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_CHECKERCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> CheckerCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_CUSTOMERCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> CustomerCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_LIAISONCOUNTRYCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> LiaisonCountryCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_REASONFORDELAYCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> ReasonForDelayCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_BSCNUMBERCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> BSCNumberCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_SERVERCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> ServerCode {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATEACCOUNTDELETION", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateAccountDeletion {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATEBF", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateBF {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATECHECKGENERATED", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateCheckGenerated {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATECHECKCOMPLETED", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateCheckCompleted {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_DAYSTOCLEAR", ResourceType=typeof(Resources))]
    		public Nullable<int> DaysToClear {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATECHECKCOMPLETEDENTERED", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateCheckCompletedEntered {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATEREMINDER", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateReminder {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATEEVIDENCEREQUESTED", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateEvidenceRequested {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATESENTTOSAT", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateSentToSAT {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATERECEIVEDBYSAT", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateReceivedBySAT {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATERECEIVEDINOPS", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateReceivedInOPS {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATEREQUESTRECEIVEDBYOPS", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateRequestReceivedByOps {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATERETURNEDBYSAT", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateReturnedBySAT {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATEVALIDATION", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateValidation {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_NOTES", ResourceType=typeof(Resources))]
    		public string Notes {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_BF_NOTES", ResourceType=typeof(Resources))]
    		public string BF_Notes {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_STAFFCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> StaffCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_TEAMCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> TeamCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_COMMANDCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> CommandCode {get; set;}
    
      		[Display(Name="LABEL_SECURITYCHECK_LOCATIONCODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> LocationCode {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATEGENERATEDMONTH", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateGeneratedMonth {get; set;}
    
      		[DataType(DataType.Date)]
    		[Display(Name="LABEL_SECURITYCHECK_DATECLEAREDMONTH", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateClearedMonth {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_SECURITYCHECK_ISACTIVE", ResourceType=typeof(Resources))]
    		public bool IsActive {get; set;}
    
        }
    }
}
