//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    public partial class StaffOfficesSearchMatchModel
    {
    
        public virtual System.Guid Code
        {
    	    get;
            set;
        }
    
        public virtual string Name
        {
    	    get;
            set;
        }
    
        public virtual string Address1
        {
    	    get;
            set;
        }
    
        public virtual string Address2
        {
    	    get;
            set;
        }
    
        public virtual string Address3
        {
    	    get;
            set;
        }
    
        public virtual string Address4
        {
    	    get;
            set;
        }
    
        public virtual string Address5
        {
    	    get;
            set;
        }
    
        public virtual string Postcode
        {
    	    get;
            set;
        }
    
        public virtual string Telephone
        {
    	    get;
            set;
        }
    
        public virtual string OpeningTimes
        {
    	    get;
            set;
        }
    }
}
