//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dwp.Adep.Framework.Management.ResourceLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FixedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FixedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dwp.Adep.Framework.Management.ResourceLibrary.FixedResources", typeof(FixedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Application.
        /// </summary>
        public static string DDL_APPLICATION {
            get {
                return ResourceManager.GetString("DDL_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0}.
        /// </summary>
        public static string DDL_GENERIC {
            get {
                return ResourceManager.GetString("DDL_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy Check.
        /// </summary>
        public static string ENTITYNAME_ACCURACYCHECK {
            get {
                return ResourceManager.GetString("ENTITYNAME_ACCURACYCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string ENTITYNAME_APPLICATION {
            get {
                return ResourceManager.GetString("ENTITYNAME_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCS Number.
        /// </summary>
        public static string ENTITYNAME_BCSNUMBER {
            get {
                return ResourceManager.GetString("ENTITYNAME_BCSNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit.
        /// </summary>
        public static string ENTITYNAME_BENEFIT {
            get {
                return ResourceManager.GetString("ENTITYNAME_BENEFIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Sub Type.
        /// </summary>
        public static string ENTITYNAME_CHECKSUBTYPE {
            get {
                return ResourceManager.GetString("ENTITYNAME_CHECKSUBTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Type.
        /// </summary>
        public static string ENTITYNAME_CHECKTYPE {
            get {
                return ResourceManager.GetString("ENTITYNAME_CHECKTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string ENTITYNAME_COMMAND {
            get {
                return ResourceManager.GetString("ENTITYNAME_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string ENTITYNAME_COUNTRY {
            get {
                return ResourceManager.GetString("ENTITYNAME_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string ENTITYNAME_CUSTOMER {
            get {
                return ResourceManager.GetString("ENTITYNAME_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Choice.
        /// </summary>
        public static string ENTITYNAME_ERRORCHOICE {
            get {
                return ResourceManager.GetString("ENTITYNAME_ERRORCHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Sub Choice.
        /// </summary>
        public static string ENTITYNAME_ERRORSUBCHOICE {
            get {
                return ResourceManager.GetString("ENTITYNAME_ERRORSUBCHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Type.
        /// </summary>
        public static string ENTITYNAME_ERRORTYPE {
            get {
                return ResourceManager.GetString("ENTITYNAME_ERRORTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string ENTITYNAME_GRADE {
            get {
                return ResourceManager.GetString("ENTITYNAME_GRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string ENTITYNAME_HOLIDAY {
            get {
                return ResourceManager.GetString("ENTITYNAME_HOLIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ENTITYNAME_LOCATION {
            get {
                return ResourceManager.GetString("ENTITYNAME_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Standard Holiday.
        /// </summary>
        public static string ENTITYNAME_NONSTANDARDHOLIDAY {
            get {
                return ResourceManager.GetString("ENTITYNAME_NONSTANDARDHOLIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string ENTITYNAME_ORGANISATION {
            get {
                return ResourceManager.GetString("ENTITYNAME_ORGANISATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation Hierarchy.
        /// </summary>
        public static string ENTITYNAME_ORGANISATIONHIERARCHY {
            get {
                return ResourceManager.GetString("ENTITYNAME_ORGANISATIONHIERARCHY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation Type.
        /// </summary>
        public static string ENTITYNAME_ORGANISATIONTYPE {
            get {
                return ResourceManager.GetString("ENTITYNAME_ORGANISATIONTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason For Delay.
        /// </summary>
        public static string ENTITYNAME_REASONFORDELAY {
            get {
                return ResourceManager.GetString("ENTITYNAME_REASONFORDELAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string ENTITYNAME_REPORTTYPE {
            get {
                return ResourceManager.GetString("ENTITYNAME_REPORTTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Number.
        /// </summary>
        public static string ENTITYNAME_SCHEDULENUMBER {
            get {
                return ResourceManager.GetString("ENTITYNAME_SCHEDULENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Check.
        /// </summary>
        public static string ENTITYNAME_SECURITYCHECK {
            get {
                return ResourceManager.GetString("ENTITYNAME_SECURITYCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string ENTITYNAME_SERVER {
            get {
                return ResourceManager.GetString("ENTITYNAME_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string ENTITYNAME_STAFF {
            get {
                return ResourceManager.GetString("ENTITYNAME_STAFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Application Details.
        /// </summary>
        public static string ENTITYNAME_STAFFAPPLICATIONDETAILS {
            get {
                return ResourceManager.GetString("ENTITYNAME_STAFFAPPLICATIONDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Details.
        /// </summary>
        public static string ENTITYNAME_STAFFDETAILS {
            get {
                return ResourceManager.GetString("ENTITYNAME_STAFFDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Offices.
        /// </summary>
        public static string ENTITYNAME_STAFFOFFICES {
            get {
                return ResourceManager.GetString("ENTITYNAME_STAFFOFFICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string ENTITYNAME_TEAM {
            get {
                return ResourceManager.GetString("ENTITYNAME_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string HTML_LANG {
            get {
                return ResourceManager.GetString("HTML_LANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string LABEL_CREATEBUTTON {
            get {
                return ResourceManager.GetString("LABEL_CREATEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LABEL_DELETEBUTTON {
            get {
                return ResourceManager.GetString("LABEL_DELETEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string LABEL_EXITBUTTON {
            get {
                return ResourceManager.GetString("LABEL_EXITBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select:.
        /// </summary>
        public static string LABEL_GRIDTITLE {
            get {
                return ResourceManager.GetString("LABEL_GRIDTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select:.
        /// </summary>
        public static string LABEL_GRIDTITLE_ADMINMENU {
            get {
                return ResourceManager.GetString("LABEL_GRIDTITLE_ADMINMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LABEL_LEGEND_SEARCH {
            get {
                return ResourceManager.GetString("LABEL_LEGEND_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string LABEL_LISTNAME {
            get {
                return ResourceManager.GetString("LABEL_LISTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string LABEL_MANAGEBUTTON {
            get {
                return ResourceManager.GetString("LABEL_MANAGEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string LABEL_NEWBUTTON {
            get {
                return ResourceManager.GetString("LABEL_NEWBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page created on.
        /// </summary>
        public static string LABEL_PAGECREATED {
            get {
                return ResourceManager.GetString("LABEL_PAGECREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Organisation.
        /// </summary>
        public static string LABEL_PARENT_ORGANISATION {
            get {
                return ResourceManager.GetString("LABEL_PARENT_ORGANISATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LABEL_SAVEBUTTON {
            get {
                return ResourceManager.GetString("LABEL_SAVEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Reference Data.
        /// </summary>
        public static string LABEL_SCREENTITLE_ADMINMENU {
            get {
                return ResourceManager.GetString("LABEL_SCREENTITLE_ADMINMENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Application and Organisation.
        /// </summary>
        public static string LABEL_SCREENTITLE_APPLICATIONORGANISATIONSELECT {
            get {
                return ResourceManager.GetString("LABEL_SCREENTITLE_APPLICATIONORGANISATIONSELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LABEL_SEARCHBUTTON {
            get {
                return ResourceManager.GetString("LABEL_SEARCHBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string LABEL_SELECTBUTTON {
            get {
                return ResourceManager.GetString("LABEL_SELECTBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Application.
        /// </summary>
        public static string LABEL_UPDATEAPPLICATIONBUTTON {
            get {
                return ResourceManager.GetString("LABEL_UPDATEAPPLICATIONBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string LABEL_UPDATEBUTTON {
            get {
                return ResourceManager.GetString("LABEL_UPDATEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string LABEL_WELCOME {
            get {
                return ResourceManager.GetString("LABEL_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Attributes.
        /// </summary>
        public static string LEGEND_APPLICATION_ATTRIBUTES {
            get {
                return ResourceManager.GetString("LEGEND_APPLICATION_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Roles.
        /// </summary>
        public static string LEGEND_APPLICATION_ROLES {
            get {
                return ResourceManager.GetString("LEGEND_APPLICATION_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Organisations.
        /// </summary>
        public static string LEGEND_AVAILABLEORGANISATIONS {
            get {
                return ResourceManager.GetString("LEGEND_AVAILABLEORGANISATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Staff Organisations for Application.
        /// </summary>
        public static string LEGEND_STAFF_ORGANISATIONS_FOR_APPLICATION {
            get {
                return ResourceManager.GetString("LEGEND_STAFF_ORGANISATIONS_FOR_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LINKTEXT_ABOUT {
            get {
                return ResourceManager.GetString("LINKTEXT_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        public static string LINKTEXT_ACCESSIBILITY {
            get {
                return ResourceManager.GetString("LINKTEXT_ACCESSIBILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string LINKTEXT_ADMIN {
            get {
                return ResourceManager.GetString("LINKTEXT_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string LINKTEXT_FEEDBACK {
            get {
                return ResourceManager.GetString("LINKTEXT_FEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string LINKTEXT_HELP {
            get {
                return ResourceManager.GetString("LINKTEXT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LINKTEXT_HOME {
            get {
                return ResourceManager.GetString("LINKTEXT_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string LINKTEXT_SITEMAP {
            get {
                return ResourceManager.GetString("LINKTEXT_SITEMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Organisation failed as an Organisation already exists with the same name.
        /// </summary>
        public static string MESSAGE_CREATEFAILED_DUE_TO_ORGANISATIONALREADY_EXISTS {
            get {
                return ResourceManager.GetString("MESSAGE_CREATEFAILED_DUE_TO_ORGANISATIONALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has not been possible to delete this item. Please set to inactive..
        /// </summary>
        public static string MESSAGE_DATACANNOTDELETE {
            get {
                return ResourceManager.GetString("MESSAGE_DATACANNOTDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has been updated since you retrieved it. Please return to the list and reselect the item..
        /// </summary>
        public static string MESSAGE_DATACONCURRENCYFAILURE {
            get {
                return ResourceManager.GetString("MESSAGE_DATACONCURRENCYFAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to delete at the moment. You are advised to mark it as &apos;Inactive&apos;.
        /// </summary>
        public static string MESSAGE_DATAEXCEPTION {
            get {
                return ResourceManager.GetString("MESSAGE_DATAEXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful.
        /// </summary>
        public static string MESSAGE_DELETE_SUCCEEDED {
            get {
                return ResourceManager.GetString("MESSAGE_DELETE_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete? Press delete again to confirm..
        /// </summary>
        public static string MESSAGE_DELETECONFIRMATION {
            get {
                return ResourceManager.GetString("MESSAGE_DELETECONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to exit? Press exit again to confirm..
        /// </summary>
        public static string MESSAGE_EXITCONFIRMATION {
            get {
                return ResourceManager.GetString("MESSAGE_EXITCONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data retrieval has failed.
        /// </summary>
        public static string MESSAGE_RETREIVAL_FAILED {
            get {
                return ResourceManager.GetString("MESSAGE_RETREIVAL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data retrieval failed..
        /// </summary>
        public static string MESSAGE_RETRIEVAL_FAILED {
            get {
                return ResourceManager.GetString("MESSAGE_RETRIEVAL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The staff member has the following user roles assigned:.
        /// </summary>
        public static string MESSAGE_STAFF_MEMBER_HAS_FOLLOWING_AD_ROLES {
            get {
                return ResourceManager.GetString("MESSAGE_STAFF_MEMBER_HAS_FOLLOWING_AD_ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Staff Member is NOT a user of this application and has no access to the system..
        /// </summary>
        public static string MESSAGE_STAFF_MEMBER_NOT_USER_OF_APPLICATION {
            get {
                return ResourceManager.GetString("MESSAGE_STAFF_MEMBER_NOT_USER_OF_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A record already exists with these details.
        /// </summary>
        public static string MESSAGE_UNIQUEKEYCONSTRAINT {
            get {
                return ResourceManager.GetString("MESSAGE_UNIQUEKEYCONSTRAINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update failed and was not saved..
        /// </summary>
        public static string MESSAGE_UPDATE_FAILED {
            get {
                return ResourceManager.GetString("MESSAGE_UPDATE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update did not complete as no application was selected..
        /// </summary>
        public static string MESSAGE_UPDATE_NOCHANGE {
            get {
                return ResourceManager.GetString("MESSAGE_UPDATE_NOCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was successful..
        /// </summary>
        public static string MESSAGE_UPDATE_SUCCEEDED {
            get {
                return ResourceManager.GetString("MESSAGE_UPDATE_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Organisation failed as the organisation with the same name already exists.
        /// </summary>
        public static string MESSAGE_UPDATEFAILED_DUE_TO_ORGANISATIONALREADY_EXISTS {
            get {
                return ResourceManager.GetString("MESSAGE_UPDATEFAILED_DUE_TO_ORGANISATIONALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string PAGING_FIRSTPAGE {
            get {
                return ResourceManager.GetString("PAGING_FIRSTPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string PAGING_LASTPAGE {
            get {
                return ResourceManager.GetString("PAGING_LASTPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PAGING_NEXT {
            get {
                return ResourceManager.GetString("PAGING_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string PAGING_PREVIOUS {
            get {
                return ResourceManager.GetString("PAGING_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWP Small Systems Framework.
        /// </summary>
        public static string SYS_NAME {
            get {
                return ResourceManager.GetString("SYS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPORARY_LABEL.
        /// </summary>
        public static string TEMPORARY_LABEL {
            get {
                return ResourceManager.GetString("TEMPORARY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the about screen.
        /// </summary>
        public static string TOOLTIP_ABOUT {
            get {
                return ResourceManager.GetString("TOOLTIP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the accessibility page.
        /// </summary>
        public static string TOOLTIP_ACCESSIBILITY {
            get {
                return ResourceManager.GetString("TOOLTIP_ACCESSIBILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the admin screen.
        /// </summary>
        public static string TOOLTIP_ADMIN {
            get {
                return ResourceManager.GetString("TOOLTIP_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string TOOLTIP_ADMINBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_ADMINBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TOOLTIP_CREATEBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_CREATEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TOOLTIP_DELETEBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_DELETEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave this page.
        /// </summary>
        public static string TOOLTIP_EXITBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_EXITBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the feedback/contact us screen.
        /// </summary>
        public static string TOOLTIP_FEEDBACK {
            get {
                return ResourceManager.GetString("TOOLTIP_FEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the help screen.
        /// </summary>
        public static string TOOLTIP_HELP {
            get {
                return ResourceManager.GetString("TOOLTIP_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the home screen.
        /// </summary>
        public static string TOOLTIP_HOME {
            get {
                return ResourceManager.GetString("TOOLTIP_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TOOLTIP_HOMEBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_HOMEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to maintain .
        /// </summary>
        public static string TOOLTIP_MAINTAIN {
            get {
                return ResourceManager.GetString("TOOLTIP_MAINTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string TOOLTIP_SAVEBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_SAVEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to edit.
        /// </summary>
        public static string TOOLTIP_SELECTTOEDITBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_SELECTTOEDITBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the site map screen.
        /// </summary>
        public static string TOOLTIP_SITEMAP {
            get {
                return ResourceManager.GetString("TOOLTIP_SITEMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update .
        /// </summary>
        public static string TOOLTIP_UPDATEBUTTON {
            get {
                return ResourceManager.GetString("TOOLTIP_UPDATEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Number should be numeric and eight digits.
        /// </summary>
        public static string VAL_STAFFNUMBER {
            get {
                return ResourceManager.GetString("VAL_STAFFNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date for {0}..
        /// </summary>
        public static string VAL_VALIDDATE {
            get {
                return ResourceManager.GetString("VAL_VALIDDATE", resourceCulture);
            }
        }
    }
}
