//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class ErrorBuilder
    {
        #region Create Method
        public static Error Create()
        {
            return new Error
            {
    				Code = Guid.NewGuid(),
    				SecurityLabel = Guid.NewGuid(),
    				TableID = 100,
    				AccuracyCheckCode = Guid.NewGuid(),
    				RaisedDate = DateTime.Now,
    				DateOccurred = DateTime.Now,
    				DateFound = DateTime.Now,
    				DaysToDetect = 100,
    				ErrorTypeCode = Guid.NewGuid(),
    				IsOverpayment = false,
    				ErrorChoiceCode = Guid.NewGuid(),
    				ErrorSubChoiceCode = Guid.NewGuid(),
    				WeeklyAmount = 1111.11M,
    				TotalAmount = 1111.11M,
    				StaffCode = Guid.NewGuid(),
    				TeamCode = Guid.NewGuid(),
    				CommandCode = Guid.NewGuid(),
    				LocationCode = Guid.NewGuid(),
    				Notes = "test Notes",
    				IsActive = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static Error WithCode(this Error error, Guid code)
        {
            error.Code = code;
            return error;
        }
       	public static Error WithSecurityLabel(this Error error, Guid securityLabel)
        {
            error.SecurityLabel = securityLabel;
            return error;
        }
       	public static Error WithTableID(this Error error, Int32 tableID)
        {
            error.TableID = tableID;
            return error;
        }
       	public static Error WithAccuracyCheckCode(this Error error, Guid accuracyCheckCode)
        {
            error.AccuracyCheckCode = accuracyCheckCode;
            return error;
        }
       	public static Error WithRaisedDate(this Error error, DateTime raisedDate)
        {
            error.RaisedDate = raisedDate;
            return error;
        }
       	public static Error WithDateOccurred(this Error error, DateTime dateOccurred)
        {
            error.DateOccurred = dateOccurred;
            return error;
        }
       	public static Error WithDateFound(this Error error, DateTime dateFound)
        {
            error.DateFound = dateFound;
            return error;
        }
       	public static Error WithDaysToDetect(this Error error, Int32 daysToDetect)
        {
            error.DaysToDetect = daysToDetect;
            return error;
        }
       	public static Error WithErrorTypeCode(this Error error, Guid errorTypeCode)
        {
            error.ErrorTypeCode = errorTypeCode;
            return error;
        }
       	public static Error WithIsOverpayment(this Error error, Boolean isOverpayment)
        {
            error.IsOverpayment = isOverpayment;
            return error;
        }
       	public static Error WithErrorChoiceCode(this Error error, Guid errorChoiceCode)
        {
            error.ErrorChoiceCode = errorChoiceCode;
            return error;
        }
       	public static Error WithErrorSubChoiceCode(this Error error, Guid errorSubChoiceCode)
        {
            error.ErrorSubChoiceCode = errorSubChoiceCode;
            return error;
        }
       	public static Error WithWeeklyAmount(this Error error, Decimal weeklyAmount)
        {
            error.WeeklyAmount = weeklyAmount;
            return error;
        }
       	public static Error WithTotalAmount(this Error error, Decimal totalAmount)
        {
            error.TotalAmount = totalAmount;
            return error;
        }
       	public static Error WithStaffCode(this Error error, Guid staffCode)
        {
            error.StaffCode = staffCode;
            return error;
        }
       	public static Error WithTeamCode(this Error error, Guid teamCode)
        {
            error.TeamCode = teamCode;
            return error;
        }
       	public static Error WithCommandCode(this Error error, Guid commandCode)
        {
            error.CommandCode = commandCode;
            return error;
        }
       	public static Error WithLocationCode(this Error error, Guid locationCode)
        {
            error.LocationCode = locationCode;
            return error;
        }
       	public static Error WithNotes(this Error error, String notes)
        {
            error.Notes = notes;
            return error;
        }
       	public static Error WithIsActive(this Error error, Boolean isActive)
        {
            error.IsActive = isActive;
            return error;
        }
       	public static Error WithAccuracyCheck(this Error error, AccuracyCheck accuracyCheck)
        {
            error.AccuracyCheck = accuracyCheck;
            return error;
        }
    
       	public static Error WithErrorChoice(this Error error, ErrorChoice errorChoice)
        {
            error.ErrorChoice = errorChoice;
            return error;
        }
    
       	public static Error WithErrorSubChoice(this Error error, ErrorSubChoice errorSubChoice)
        {
            error.ErrorSubChoice = errorSubChoice;
            return error;
        }
    
       	public static Error WithErrorType(this Error error, ErrorType errorType)
        {
            error.ErrorType = errorType;
            return error;
        }
    
       	public static Error WithOrganisation(this Error error, Organisation organisation)
        {
            error.Organisation = organisation;
            return error;
        }
    
       	public static Error WithOrganisation1(this Error error, Organisation organisation1)
        {
            error.Organisation1 = organisation1;
            return error;
        }
    
       	public static Error WithOrganisation2(this Error error, Organisation organisation2)
        {
            error.Organisation2 = organisation2;
            return error;
        }
    
       	public static Error WithOrganisation3(this Error error, Organisation organisation3)
        {
            error.Organisation3 = organisation3;
            return error;
        }
    

        #endregion
    }
}
