//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class ErrorTypeBuilder
    {
        #region Create Method
        public static ErrorType Create()
        {
            return new ErrorType
            {
    				Code = Guid.NewGuid(),
    				SecurityLabel = Guid.NewGuid(),
    				Description = "test Description",
    				IsActive = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ErrorType WithCode(this ErrorType errorType, Guid code)
        {
            errorType.Code = code;
            return errorType;
        }
       	public static ErrorType WithSecurityLabel(this ErrorType errorType, Guid securityLabel)
        {
            errorType.SecurityLabel = securityLabel;
            return errorType;
        }
       	public static ErrorType WithDescription(this ErrorType errorType, String description)
        {
            errorType.Description = description;
            return errorType;
        }
       	public static ErrorType WithIsActive(this ErrorType errorType, Boolean isActive)
        {
            errorType.IsActive = isActive;
            return errorType;
        }
       	public static ErrorType WithError(this ErrorType errorType, ICollection< Error> error)
        {
            errorType.Error = error;
            return errorType;
        }
    
       	public static ErrorType WithOrganisation(this ErrorType errorType, Organisation organisation)
        {
            errorType.Organisation = organisation;
            return errorType;
        }
    

        #endregion
    }
}
