//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class ErrorChoiceBuilder
    {
        #region Create Method
        public static ErrorChoice Create()
        {
            return new ErrorChoice
            {
    				Code = Guid.NewGuid(),
    				SecurityLabel = Guid.NewGuid(),
    				Description = "test Description",
    				IsActive = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ErrorChoice WithCode(this ErrorChoice errorChoice, Guid code)
        {
            errorChoice.Code = code;
            return errorChoice;
        }
       	public static ErrorChoice WithSecurityLabel(this ErrorChoice errorChoice, Guid securityLabel)
        {
            errorChoice.SecurityLabel = securityLabel;
            return errorChoice;
        }
       	public static ErrorChoice WithDescription(this ErrorChoice errorChoice, String description)
        {
            errorChoice.Description = description;
            return errorChoice;
        }
       	public static ErrorChoice WithIsActive(this ErrorChoice errorChoice, Boolean isActive)
        {
            errorChoice.IsActive = isActive;
            return errorChoice;
        }
       	public static ErrorChoice WithError(this ErrorChoice errorChoice, ICollection< Error> error)
        {
            errorChoice.Error = error;
            return errorChoice;
        }
    
       	public static ErrorChoice WithOrganisation(this ErrorChoice errorChoice, Organisation organisation)
        {
            errorChoice.Organisation = organisation;
            return errorChoice;
        }
    
       	public static ErrorChoice WithErrorSubChoice(this ErrorChoice errorChoice, ICollection< ErrorSubChoice> errorSubChoice)
        {
            errorChoice.ErrorSubChoice = errorSubChoice;
            return errorChoice;
        }
    

        #endregion
    }
}
