//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class GradeBuilder
    {
        #region Create Method
        public static Grade Create()
        {
            return new Grade
            {
    				Code = Guid.NewGuid(),
    				SecurityLabel = Guid.NewGuid(),
    				Grade1 = "test Grade1",
    				DateDeleted = DateTime.Now,
    				IsActive = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static Grade WithCode(this Grade grade, Guid code)
        {
            grade.Code = code;
            return grade;
        }
       	public static Grade WithSecurityLabel(this Grade grade, Guid securityLabel)
        {
            grade.SecurityLabel = securityLabel;
            return grade;
        }
       	public static Grade WithGrade1(this Grade grade, String grade1)
        {
            grade.Grade1 = grade1;
            return grade;
        }
       	public static Grade WithDateDeleted(this Grade grade, DateTime dateDeleted)
        {
            grade.DateDeleted = dateDeleted;
            return grade;
        }
       	public static Grade WithIsActive(this Grade grade, Boolean isActive)
        {
            grade.IsActive = isActive;
            return grade;
        }
       	public static Grade WithOrganisation(this Grade grade, Organisation organisation)
        {
            grade.Organisation = organisation;
            return grade;
        }
    
       	public static Grade WithStaff(this Grade grade, ICollection< Staff> staff)
        {
            grade.Staff = staff;
            return grade;
        }
    

        #endregion
    }
}
