//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class ImportStaffBuilder
    {
        #region Create Method
        public static ImportStaff Create()
        {
            return new ImportStaff
            {
    				Code = Guid.NewGuid(),
    				StaffNumber = "test StaffNumber",
    				LastName = "test LastName",
    				FirstName = "test FirstName",
    				NetworkLastName = "test NetworkLastName",
    				NetworkFirstName = "test NetworkFirstName",
    				GradeID = 100,
    				TeamID = 100,
    				CommandID = 100,
    				LocationID = 100,
    				NonIPC = false,
    				LeftIPC = DateTime.Now,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ImportStaff WithCode(this ImportStaff importStaff, Guid code)
        {
            importStaff.Code = code;
            return importStaff;
        }
       	public static ImportStaff WithStaffNumber(this ImportStaff importStaff, String staffNumber)
        {
            importStaff.StaffNumber = staffNumber;
            return importStaff;
        }
       	public static ImportStaff WithLastName(this ImportStaff importStaff, String lastName)
        {
            importStaff.LastName = lastName;
            return importStaff;
        }
       	public static ImportStaff WithFirstName(this ImportStaff importStaff, String firstName)
        {
            importStaff.FirstName = firstName;
            return importStaff;
        }
       	public static ImportStaff WithNetworkLastName(this ImportStaff importStaff, String networkLastName)
        {
            importStaff.NetworkLastName = networkLastName;
            return importStaff;
        }
       	public static ImportStaff WithNetworkFirstName(this ImportStaff importStaff, String networkFirstName)
        {
            importStaff.NetworkFirstName = networkFirstName;
            return importStaff;
        }
       	public static ImportStaff WithGradeID(this ImportStaff importStaff, Int32 gradeID)
        {
            importStaff.GradeID = gradeID;
            return importStaff;
        }
       	public static ImportStaff WithTeamID(this ImportStaff importStaff, Int32 teamID)
        {
            importStaff.TeamID = teamID;
            return importStaff;
        }
       	public static ImportStaff WithCommandID(this ImportStaff importStaff, Int32 commandID)
        {
            importStaff.CommandID = commandID;
            return importStaff;
        }
       	public static ImportStaff WithLocationID(this ImportStaff importStaff, Int32 locationID)
        {
            importStaff.LocationID = locationID;
            return importStaff;
        }
       	public static ImportStaff WithNonIPC(this ImportStaff importStaff, Boolean nonIPC)
        {
            importStaff.NonIPC = nonIPC;
            return importStaff;
        }
       	public static ImportStaff WithLeftIPC(this ImportStaff importStaff, DateTime leftIPC)
        {
            importStaff.LeftIPC = leftIPC;
            return importStaff;
        }

        #endregion
    }
}
