//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class OrganisationTypeBuilder
    {
        #region Create Method
        public static OrganisationType Create()
        {
            return new OrganisationType
            {
    				Code = Guid.NewGuid(),
    				Name = "test Name",
    				OrganisationTypeGroupCode = Guid.NewGuid(),
    				ParentOrganisationTypeCode = Guid.NewGuid(),
    				IsActive = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static OrganisationType WithCode(this OrganisationType organisationType, Guid code)
        {
            organisationType.Code = code;
            return organisationType;
        }
       	public static OrganisationType WithName(this OrganisationType organisationType, String name)
        {
            organisationType.Name = name;
            return organisationType;
        }
       	public static OrganisationType WithOrganisationTypeGroupCode(this OrganisationType organisationType, Guid organisationTypeGroupCode)
        {
            organisationType.OrganisationTypeGroupCode = organisationTypeGroupCode;
            return organisationType;
        }
       	public static OrganisationType WithParentOrganisationTypeCode(this OrganisationType organisationType, Guid parentOrganisationTypeCode)
        {
            organisationType.ParentOrganisationTypeCode = parentOrganisationTypeCode;
            return organisationType;
        }
       	public static OrganisationType WithIsActive(this OrganisationType organisationType, Boolean isActive)
        {
            organisationType.IsActive = isActive;
            return organisationType;
        }
       	public static OrganisationType WithOrganisation(this OrganisationType organisationType, ICollection< Organisation> organisation)
        {
            organisationType.Organisation = organisation;
            return organisationType;
        }
    
       	public static OrganisationType WithOrganisationTypeGroup(this OrganisationType organisationType, OrganisationTypeGroup organisationTypeGroup)
        {
            organisationType.OrganisationTypeGroup = organisationTypeGroup;
            return organisationType;
        }
    
       	public static OrganisationType WithOrganisationType1(this OrganisationType organisationType, ICollection< OrganisationType> organisationType1)
        {
            organisationType.OrganisationType1 = organisationType1;
            return organisationType;
        }
    
       	public static OrganisationType WithOrganisationType2(this OrganisationType organisationType, OrganisationType organisationType2)
        {
            organisationType.OrganisationType2 = organisationType2;
            return organisationType;
        }
    

        #endregion
    }
}
