//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class ReferredBuilder
    {
        #region Create Method
        public static Referred Create()
        {
            return new Referred
            {
    				Code = Guid.NewGuid(),
    				SecurityLabel = Guid.NewGuid(),
    				Description = "test Description",
    				IsActive = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static Referred WithCode(this Referred referred, Guid code)
        {
            referred.Code = code;
            return referred;
        }
       	public static Referred WithSecurityLabel(this Referred referred, Guid securityLabel)
        {
            referred.SecurityLabel = securityLabel;
            return referred;
        }
       	public static Referred WithDescription(this Referred referred, String description)
        {
            referred.Description = description;
            return referred;
        }
       	public static Referred WithIsActive(this Referred referred, Boolean isActive)
        {
            referred.IsActive = isActive;
            return referred;
        }
       	public static Referred WithOrganisation(this Referred referred, Organisation organisation)
        {
            referred.Organisation = organisation;
            return referred;
        }
    

        #endregion
    }
}
