//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class ReportTypeBuilder
    {
        #region Create Method
        public static ReportType Create()
        {
            return new ReportType
            {
    				Code = Guid.NewGuid(),
    				SecurityLabel = Guid.NewGuid(),
    				Description = "test Description",
    				ApplicationCode = Guid.NewGuid(),
    				IsACTReport = false,
    				IsOpsReport = false,
    				IsSATReport = false,
    				IsActive = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static ReportType WithCode(this ReportType reportType, Guid code)
        {
            reportType.Code = code;
            return reportType;
        }
       	public static ReportType WithSecurityLabel(this ReportType reportType, Guid securityLabel)
        {
            reportType.SecurityLabel = securityLabel;
            return reportType;
        }
       	public static ReportType WithDescription(this ReportType reportType, String description)
        {
            reportType.Description = description;
            return reportType;
        }
       	public static ReportType WithApplicationCode(this ReportType reportType, Guid applicationCode)
        {
            reportType.ApplicationCode = applicationCode;
            return reportType;
        }
       	public static ReportType WithIsACTReport(this ReportType reportType, Boolean isACTReport)
        {
            reportType.IsACTReport = isACTReport;
            return reportType;
        }
       	public static ReportType WithIsOpsReport(this ReportType reportType, Boolean isOpsReport)
        {
            reportType.IsOpsReport = isOpsReport;
            return reportType;
        }
       	public static ReportType WithIsSATReport(this ReportType reportType, Boolean isSATReport)
        {
            reportType.IsSATReport = isSATReport;
            return reportType;
        }
       	public static ReportType WithIsActive(this ReportType reportType, Boolean isActive)
        {
            reportType.IsActive = isActive;
            return reportType;
        }
       	public static ReportType WithApplication(this ReportType reportType, Application application)
        {
            reportType.Application = application;
            return reportType;
        }
    
       	public static ReportType WithOrganisation(this ReportType reportType, Organisation organisation)
        {
            reportType.Organisation = organisation;
            return reportType;
        }
    
       	public static ReportType WithOrganisation1(this ReportType reportType, Organisation organisation1)
        {
            reportType.Organisation1 = organisation1;
            return reportType;
        }
    

        #endregion
    }
}
