//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Dwp.Adep.Framework.Management.DataServices;
using Dwp.Adep.Framework.Management.DataServices.Models;

namespace Dwp.Adep.Framework.Management.DataServices.Tests.TestEntityBuilder
{
    public static partial class StaffOrganisationBuilder
    {
        #region Create Method
        public static StaffOrganisation Create()
        {
            return new StaffOrganisation
            {
    				Code = Guid.NewGuid(),
    				StaffCode = Guid.NewGuid(),
    				OrganisationCode = Guid.NewGuid(),
    				ApplicationCode = Guid.NewGuid(),
    				IsDefault = false,
    				IsCurrent = false,
    				RowIdentifier = null
            };
        }

        #endregion
    
        #region With Methods
       	public static StaffOrganisation WithCode(this StaffOrganisation staffOrganisation, Guid code)
        {
            staffOrganisation.Code = code;
            return staffOrganisation;
        }
       	public static StaffOrganisation WithStaffCode(this StaffOrganisation staffOrganisation, Guid staffCode)
        {
            staffOrganisation.StaffCode = staffCode;
            return staffOrganisation;
        }
       	public static StaffOrganisation WithOrganisationCode(this StaffOrganisation staffOrganisation, Guid organisationCode)
        {
            staffOrganisation.OrganisationCode = organisationCode;
            return staffOrganisation;
        }
       	public static StaffOrganisation WithApplicationCode(this StaffOrganisation staffOrganisation, Guid applicationCode)
        {
            staffOrganisation.ApplicationCode = applicationCode;
            return staffOrganisation;
        }
       	public static StaffOrganisation WithIsDefault(this StaffOrganisation staffOrganisation, Boolean isDefault)
        {
            staffOrganisation.IsDefault = isDefault;
            return staffOrganisation;
        }
       	public static StaffOrganisation WithIsCurrent(this StaffOrganisation staffOrganisation, Boolean isCurrent)
        {
            staffOrganisation.IsCurrent = isCurrent;
            return staffOrganisation;
        }
       	public static StaffOrganisation WithApplication(this StaffOrganisation staffOrganisation, Application application)
        {
            staffOrganisation.Application = application;
            return staffOrganisation;
        }
    
       	public static StaffOrganisation WithOrganisation(this StaffOrganisation staffOrganisation, Organisation organisation)
        {
            staffOrganisation.Organisation = organisation;
            return staffOrganisation;
        }
    
       	public static StaffOrganisation WithStaff(this StaffOrganisation staffOrganisation, Staff staff)
        {
            staffOrganisation.Staff = staff;
            return staffOrganisation;
        }
    

        #endregion
    }
}
