//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.Web.Models;

namespace Dwp.Adep.Framework.Management.Web.ViewModels
{
    public partial class SecurityCheckVM
    {
    	public SecurityCheckModel SecurityCheckItem { get; set; }
    
    	public List<StaffModel> CheckerList { get; set; }
    	public List<CustomerModel> CustomerList { get; set; }
    	public List<CountryModel> LiaisonCountryList { get; set; }
    	public List<ReasonForDelayModel> ReasonForDelayList { get; set; }
    	public List<BCSNumberModel> BSCNumberList { get; set; }
    	public List<ServerModel> ServerList { get; set; }
    	public List<StaffModel> StaffList { get; set; }
    	public List<OrganisationModel> TeamList { get; set; }
    	public List<OrganisationModel> CommandList { get; set; }
    	public List<OrganisationModel> LocationList { get; set; }
        public string Message { get; set; }
    
        public string IsDeleteConfirmed { get; set; }
        public string IsExitConfirmed { get; set; }
        public string IsNewConfirmed { get; set; }
    	public bool IsViewDirty { get; set; }
    
        public SecurityCheckAccessContext AccessContext { get; set; }
    	
    }
    
    public enum SecurityCheckAccessContext
    {
        Create,
        View,
        Edit
    }
}
