//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Dwp.Adep.Framework.Management.WebServices.DataContracts
{
    [DataContract]
    public partial class ApplicationAttributeVMDC
    {
    	[DataMember]
        public ApplicationAttributeDC ApplicationAttributeItem { get; set;}
    
    	[DataMember]
        public List<ApplicationAttributeDC> ApplicationAttributeList { get; set;}
    
    	//Code
    	//ApplicationCode
    	//ApplicationCode
    	[DataMember]
    	public List<ApplicationDC> ApplicationList { get; set; }
    
    	//AttributeName
    	//AttributeType
    	//IsDataSecurity
    	//IsActive
    	//IsRole
    	//RowIdentifier
    	[DataMember]
    	public string Message { get; set; }
    }
}
