//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Dwp.Adep.Framework.Management.WebServices.DataContracts
{
    [DataContract]
    public partial class CountrySearchCriteriaDC
    {
    
    	[DataMember]
        public virtual string Description
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual bool IsFrozenRate
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual bool IsEC
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual bool IsRA
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual bool IsANZAC
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Nationality
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string CountryCode
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Notes
        {
    	    get;
            set;
        }
    }
}
