//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Dwp.Adep.Framework.Management.WebServices.DataContracts
{
    [DataContract]
    public partial class LastUpdateVMDC
    {
    	[DataMember]
        public LastUpdateDC LastUpdateItem { get; set;}
    
    	[DataMember]
        public List<LastUpdateDC> LastUpdateList { get; set;}
    
    	//Code
    	//DateLastUpdate
    	//IsActive
    	//RowIdentifier
    	[DataMember]
    	public string Message { get; set; }
    }
}
