//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace Dwp.Adep.Framework.Management.WebServices.DataContracts
{
    [DataContract]
    public partial class StaffOfficesSearchCriteriaDC
    {
    
    	[DataMember]
        public virtual string Name
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Address1
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Address2
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Address3
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Address4
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Address5
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Postcode
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string Telephone
        {
    	    get;
            set;
        }
    
    	[DataMember]
        public virtual string OpeningTimes
        {
    	    get;
            set;
        }
    }
}
