//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Framework.Management.DataServices.Models
{
    public partial class ApplicationAttributeExtension : IAuditable
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual System.Guid ApplicationAttributeCode
        {
            get { return _applicationAttributeCode; }
            set
            {
                if (_applicationAttributeCode != value)
                {
                    if (ApplicationAttribute != null && ApplicationAttribute.Code != value)
                    {
                        ApplicationAttribute = null;
                    }
                    _applicationAttributeCode = value;
                }
            }
        }
        private System.Guid _applicationAttributeCode;
    
        public virtual bool IsStaffAdmin
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ApplicationAttribute ApplicationAttribute
        {
            get { return _applicationAttribute; }
            set
            {
                if (!ReferenceEquals(_applicationAttribute, value))
                {
                    var previousValue = _applicationAttribute;
                    _applicationAttribute = value;
                    FixupApplicationAttribute(previousValue);
                }
            }
        }
        private ApplicationAttribute _applicationAttribute;

        #endregion
        #region Association Fixup
    
        private void FixupApplicationAttribute(ApplicationAttribute previousValue)
        {
            if (previousValue != null && previousValue.ApplicationAttributeExtension.Contains(this))
            {
                previousValue.ApplicationAttributeExtension.Remove(this);
            }
    
            if (ApplicationAttribute != null)
            {
                if (!ApplicationAttribute.ApplicationAttributeExtension.Contains(this))
                {
                    ApplicationAttribute.ApplicationAttributeExtension.Add(this);
                }
                if (ApplicationAttributeCode != ApplicationAttribute.Code)
                {
                    ApplicationAttributeCode = ApplicationAttribute.Code;
                }
            }
        }

        #endregion
    }
}
