//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Framework.Management.DataServices.Models
{
    public partial class ImportStaff
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual string StaffNumber
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string NetworkLastName
        {
            get;
            set;
        }
    
        public virtual string NetworkFirstName
        {
            get;
            set;
        }
    
        public virtual Nullable<int> GradeID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TeamID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CommandID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LocationID
        {
            get;
            set;
        }
    
        public virtual bool NonIPC
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LeftIPC
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
    }
}
