//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Framework.Management.DataServices.Models
{
    [MetadataTypeAttribute(typeof(Staff.StaffMetadata))]
    public partial class Staff : IStaff
    {
    	public partial class StaffMetadata
    	{
    		[Key]
    		public System.Guid Code{get; set;}
    	
    		[Association("FK_Staff_Grade", "GradeCode", "Code", IsForeignKey = true)]
    		public virtual Grade Grade
    		{get; set;}
    
    	
    		[Association("FK_Staff_Organisation", "SecurityLabel", "Code", IsForeignKey = true)]
    		public virtual Organisation Organisation
    		{get; set;}
    
    	
    		[Association("FK_StaffAttributes_Staff", "Code", "StaffCode", IsForeignKey = false)]
    		public virtual ICollection<StaffAttributes> StaffAttributes
    		{get; set;}
    
    	
    		[Association("FK_StaffDetails_Staff", "Code", "StaffCode", IsForeignKey = false)]
    		public virtual ICollection<StaffDetails> StaffDetails
    		{get; set;}
    
    	
    		[Association("FK_StaffOrganisation_Staff", "Code", "StaffCode", IsForeignKey = false)]
    		public virtual ICollection<StaffOrganisation> StaffOrganisation
    		{get; set;}
    
    		}
    }
}
