//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace Dwp.Adep.Framework.Management.DataServices.Models
{
    public partial class UploadErrorLog : IAuditable, IActiveAware 
    {
        #region Primitive Properties
    
        public virtual System.Guid Code
        {
            get;
            set;
        }
    
        public virtual System.Guid UploadCode
        {
            get { return _uploadCode; }
            set
            {
                if (_uploadCode != value)
                {
                    if (UploadQueue != null && UploadQueue.Code != value)
                    {
                        UploadQueue = null;
                    }
                    _uploadCode = value;
                }
            }
        }
        private System.Guid _uploadCode;
    
        public virtual string ErrorMessage
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual byte[] RowIdentifier
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual UploadQueue UploadQueue
        {
            get { return _uploadQueue; }
            set
            {
                if (!ReferenceEquals(_uploadQueue, value))
                {
                    var previousValue = _uploadQueue;
                    _uploadQueue = value;
                    FixupUploadQueue(previousValue);
                }
            }
        }
        private UploadQueue _uploadQueue;

        #endregion
        #region Association Fixup
    
        private void FixupUploadQueue(UploadQueue previousValue)
        {
            if (previousValue != null && previousValue.UploadErrorLog.Contains(this))
            {
                previousValue.UploadErrorLog.Remove(this);
            }
    
            if (UploadQueue != null)
            {
                if (!UploadQueue.UploadErrorLog.Contains(this))
                {
                    UploadQueue.UploadErrorLog.Add(this);
                }
                if (UploadCode != UploadQueue.Code)
                {
                    UploadCode = UploadQueue.Code;
                }
            }
        }

        #endregion
    }
}
