//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;
using Dwp.Adep.Framework.Management.Web.DataAnnotation;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(AuditModel.AuditModelMetadata))]
    public partial class AuditModel
    {
    	public partial class AuditModelMetadata
    	{
    		[Key]
    		[Required]
    		[Tooltip("TOOLTIP_AUDIT_CODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_AUDIT_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[StringLength(150)]
    		[Tooltip("TOOLTIP_AUDIT_TYPEOFOBJECT", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_AUDIT_TYPEOFOBJECT", ResourceType=typeof(Resources))]
    		public string TypeOfObject {get; set;}
    
      		[StringLength(50)]
    		[Tooltip("TOOLTIP_AUDIT_AUDITACTION", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_AUDIT_AUDITACTION", ResourceType=typeof(Resources))]
    		public string AuditAction {get; set;}
    
      		[StringLength(50)]
    		[Tooltip("TOOLTIP_AUDIT_OBJECTCODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_AUDIT_OBJECTCODE", ResourceType=typeof(Resources))]
    		public string ObjectCode {get; set;}
    
      		[DataType(DataType.Date)]
    		[Tooltip("TOOLTIP_AUDIT_DATEUPDATED", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_AUDIT_DATEUPDATED", ResourceType=typeof(Resources))]
    		public Nullable<System.DateTime> DateUpdated {get; set;}
    
      		[StringLength(100)]
    		[Tooltip("TOOLTIP_AUDIT_CHANGEDBY", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_AUDIT_CHANGEDBY", ResourceType=typeof(Resources))]
    		public string ChangedBy {get; set;}
    
      		[Tooltip("TOOLTIP_AUDIT_AUDITTEXT", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_AUDIT_AUDITTEXT", ResourceType=typeof(Resources))]
    		public string AuditText {get; set;}
    
        }
    }
}
