//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;
using Dwp.Adep.Framework.Management.Web.DataAnnotation;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(NonStandardHolidayModel.NonStandardHolidayModelMetadata))]
    public partial class NonStandardHolidayModel
    {
    	public partial class NonStandardHolidayModelMetadata
    	{
    		[Key]
    		[Required]
    		[Tooltip("TOOLTIP_NONSTANDARDHOLIDAY_CODE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_NONSTANDARDHOLIDAY_CODE", ResourceType=typeof(Resources))]
    		public System.Guid Code {get; set;}
    
      		[Required]
    		[Tooltip("TOOLTIP_NONSTANDARDHOLIDAY_DATE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_NONSTANDARDHOLIDAY_DATE", ResourceType=typeof(Resources))]
    		public System.DateTime Date {get; set;}
    
      		[StringLength(100)]
    		[Tooltip("TOOLTIP_NONSTANDARDHOLIDAY_COUNTRY", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_NONSTANDARDHOLIDAY_COUNTRY", ResourceType=typeof(Resources))]
    		public string Country {get; set;}
    
      		[Required]
    		[StringLength(30)]
    		[Tooltip("TOOLTIP_NONSTANDARDHOLIDAY_DESCRIPTION", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_NONSTANDARDHOLIDAY_DESCRIPTION", ResourceType=typeof(Resources))]
    		public string Description {get; set;}
    
      		[Required]
    		[Tooltip("TOOLTIP_NONSTANDARDHOLIDAY_ISACTIVE", ResourceType=typeof(Resources))]
    		[Display(Name="LABEL_NONSTANDARDHOLIDAY_ISACTIVE", ResourceType=typeof(Resources))]
    		public bool IsActive {get; set;}
    
        }
    }
}
