//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(OrganisationTypeSearchCriteriaModel.OrganisationTypeSearchCriteriaModelMetadata))]
    public partial class OrganisationTypeSearchCriteriaModel
    {
    	public partial class OrganisationTypeSearchCriteriaModelMetadata
    	{
    		[Required]
    		[StringLength(100)]
    		[Display(Name="LABEL_ORGANISATIONTYPE_NAME", ResourceType=typeof(Resources))]
    		public string Name {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_ORGANISATIONTYPE_LEVELNUMBER", ResourceType=typeof(Resources))]
    		public int LevelNumber {get; set;}
    
      		[Required]
    		[Display(Name="LABEL_ORGANISATIONTYPE_ORGANISATIONTYPEGROUPCODE", ResourceType=typeof(Resources))]
    		public System.Guid OrganisationTypeGroupCode {get; set;}
    
      		[Display(Name="LABEL_ORGANISATIONTYPE_PARENTORGANISATIONTYPECODE", ResourceType=typeof(Resources))]
    		public Nullable<System.Guid> ParentOrganisationTypeCode {get; set;}
    
        }
    }
}
