//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using Dwp.Adep.Framework.Management.ResourceLibrary;

namespace Dwp.Adep.Framework.Management.Web.Models
{
    [MetadataTypeAttribute(typeof(OrganisationTypeGroupSearchCriteriaModel.OrganisationTypeGroupSearchCriteriaModelMetadata))]
    public partial class OrganisationTypeGroupSearchCriteriaModel
    {
    	public partial class OrganisationTypeGroupSearchCriteriaModelMetadata
    	{
    		[Required]
    		[StringLength(50)]
    		[Display(Name="LABEL_ORGANISATIONTYPEGROUP_NAME", ResourceType=typeof(Resources))]
    		public string Name {get; set;}
    
        }
    }
}
