ALTER TABLE [dbo].[Holiday]
    ADD CONSTRAINT [CK_Holiday_Date_Unique] UNIQUE NONCLUSTERED ([Date] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

