ALTER TABLE [dbo].[Staff]
    ADD CONSTRAINT [UK_Staff_StaffNumber] UNIQUE NONCLUSTERED ([StaffNumber] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

