-- =============================================
-- Script Template
-- =============================================
USE [master]
GO

/****** Object:  Database [AdepFrameworkTestDB]    Script Date: 02/21/2012 18:37:12 ******/
CREATE DATABASE [AdepFrameworkTestDB] ON  PRIMARY 
( NAME = N'AdepFrameworkTestDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL1\MSSQL\DATA\AdepFrameworkTestDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [Data1]  DEFAULT 
( NAME = N'AdepFrameworkTestDB_Data1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL1\MSSQL\DATA\AdepFrameworkTestDB_Data1.ndf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [Data2] 
( NAME = N'AdepFrameworkTestDB_Data2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL1\MSSQL\DATA\AdepFrameworkTestDB_Data2.ndf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [Indexes] 
( NAME = N'AdepFrameworkTestDB_Indexes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL1\MSSQL\DATA\AdepFrameworkTestDB_Indexes.ndf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'AdepFrameworkTestDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQL1\MSSQL\DATA\AdepFrameworkTestDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 51200KB )
GO

ALTER DATABASE [AdepFrameworkTestDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdepFrameworkTestDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdepFrameworkTestDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET  READ_WRITE 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET RECOVERY FULL 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET  MULTI_USER 
GO

ALTER DATABASE [AdepFrameworkTestDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdepFrameworkTestDB] SET DB_CHAINING OFF 
GO


